
  SELECT "CEN_OUT_MEALS"."NDETAIL_KEY",   
         "CEN_OUT_MEALS"."NTRANSACTION",   
         "CEN_OUT_MEALS"."NRESULT_KEY",   
         "CEN_OUT_MEALS"."NHANDLING_KEY",   
         "CEN_OUT_MEALS"."NHANDLING_DETAIL_KEY",   
         "CEN_OUT_MEALS"."CHANDLING_TEXT",   
         "CEN_OUT_MEALS"."NCOVER_KEY",   
         "CEN_OUT_MEALS"."CCOVER_TEXT",   
         "CEN_OUT_MEALS"."NCOVER_PRIO",   
         "CEN_OUT_MEALS"."NHANDLING_MEAL_KEY",   
         "CEN_OUT_MEALS"."NCLASS_NUMBER",   
         "CEN_OUT_MEALS"."CCLASS",   
         "CEN_OUT_MEALS"."NRESERVE_QUANTITY",   
         "CEN_OUT_MEALS"."NRESERVE_TYPE",   
         "CEN_OUT_MEALS"."NTOPOFF_QUANTITY",   
         "CEN_OUT_MEALS"."NTOPOFF_TYPE",   
         "CEN_OUT_MEALS"."NROTATION_KEY",   
         "CEN_OUT_MEALS"."NROTATION_NAME_KEY",   
         "CEN_OUT_MEALS"."CROTATION",   
         "CEN_OUT_MEALS"."NMODULE_TYPE",   
         "CEN_OUT_MEALS"."NPRIO",   
         "CEN_OUT_MEALS"."NPACKINGLIST_INDEX_KEY",   
         "CEN_OUT_MEALS"."CPACKINGLIST",   
         "CEN_OUT_MEALS"."CUNIT",   
         "CEN_OUT_MEALS"."CMEAL_CONTROL_CODE",   
         "CEN_OUT_MEALS"."CPRODUCTION_TEXT",   
         "CEN_OUT_MEALS"."NCOMPONENT_GROUP",   
         "CEN_OUT_MEALS"."NFOREIGN_OBJECT",   
         "CEN_OUT_MEALS"."NFOREIGN_GROUP",   
         "CEN_OUT_MEALS"."NASK4PASSENGER",   
         "CEN_OUT_MEALS"."CQUESTION_TEXT",   
         "CEN_OUT_MEALS"."NPASSENGER_GROUP",   
         "CEN_OUT_MEALS"."NQUANTITY_GROUP",   
         "CEN_OUT_MEALS"."CREMARK",   
         "CEN_OUT_MEALS"."NACCOUNT_KEY",   
         "CEN_OUT_MEALS"."CACCOUNT",   
         "CEN_OUT_MEALS"."NBILLING_STATUS",   
         "CEN_OUT_MEALS"."NCALC_ID",   
         "CEN_OUT_MEALS"."NCALC_DETAIL_KEY",   
         "CEN_OUT_MEALS"."NPERCENTAGE",   
         "CEN_OUT_MEALS"."NVALUE",   
         "CEN_OUT_MEALS"."NSPML_DEDUCTION",   
         "CEN_OUT_MEALS"."NAC_TRANSFER",   
         "CEN_OUT_MEALS"."NPAX",   
         "CEN_OUT_MEALS"."NPAX_MANUAL",   
         "CEN_OUT_MEALS"."NCALC_BASIS",   
         "CEN_OUT_MEALS"."NQUANTITY",   
         "CEN_OUT_MEALS"."NQUANTITY_OLD",   
         "CEN_OUT_MEALS"."NMANUAL_INPUT",   
         "CEN_OUT_MEALS"."NMANUAL_PROCESSING",   
         "CEN_OUT_MEALS"."DTIMESTAMP",   
         "CEN_OUT_MEALS"."NSTATUS",   
         "CEN_OUT_MEALS"."CDESCRIPTION",   
         "CEN_OUT_MEALS"."NQUANTITY1",   
         "CEN_OUT_MEALS"."NQUANTITY2",   
         "CEN_OUT_MEALS"."NQUANTITY3",   
         "CEN_OUT_MEALS"."NQUANTITY4",   
         "CEN_OUT_MEALS"."NQUANTITY5",   
         "CEN_OUT_MEALS"."NQUANTITY6",   
         "CEN_OUT_MEALS"."NQUANTITY7",   
         "CEN_OUT_MEALS"."NSPML_QUANTITY",   
         "CEN_OUT_MEALS"."CAREA_HOST",   
         "CEN_OUT_MEALS"."CEFFORT_HOST",   
         "CEN_OUT_MEALS"."CADDITIONAL_ACCOUNT",   
         "CEN_OUT_MEALS"."NPLTYPE_KEY",   
         "CEN_OUT_MEALS"."NPL_KIND_KEY",   
         "CEN_OUT_MEALS"."NPACKINGLIST_KEY",   
         "CEN_OUT_MEALS"."NPACKINGLIST_DETAIL_KEY",   
         "CEN_OUT_MEALS"."CTEXT",   
         "CEN_OUT_MEALS"."NDISTRIBUTE",   
         "CEN_OUT_MEALS"."NPOSTING_TYPE",   
         "CEN_OUT_MEALS"."NSALES_PRICE",   
         "CEN_OUT_MEALS"."NDELIVERY_NOTE",   
         "CEN_OUT_MEALS"."CDELIVERY_SNR",   
         "CEN_OUT_MEALS"."CDELIVERY_TEXT",   
         "CEN_OUT_MEALS"."NCONTROLLING",   
         "CEN_OUT_MEALS"."NSYSACCOUNT_KEY",   
         "CEN_OUT_MEALS"."CCODE",   
         "CEN_OUT_MEALS"."NREMITTANCEPRICE",   
         "CEN_OUT_MEALS"."NDISCOUNT",   
         "CEN_OUT_MEALS"."NPORTFEE",   
         "CEN_OUT_MEALS"."NVAT_VALUE",   
         "CEN_OUT_MEALS"."NINVOICE_CYCLE_KEY",   
         "CEN_OUT_MEALS"."NCOST_PRICE",   
         "CEN_OUT_MEALS"."NINVOICE_STATUS",   
         "CEN_OUT_MEALS"."CCLASSES",   
         "CEN_OUT_MEALS"."NSALES_PRICE_MODIFIED",   
         "CEN_OUT_MEALS"."NPRICE_CALC_TYPE",   
         "CEN_OUT_MEALS"."NCOSTTYPE",   
         "CEN_OUT_MEALS"."CTAXCODE",   
         "CEN_OUT_MEALS"."NBILLING_PRICE",   
         "CEN_OUT_MEALS"."NRELEASE_EXCLUSION",   
         "CEN_OUT_MEALS"."NSTATIONENTRY",   
         "CEN_OUT_MEALS"."CCUSTOMER_PL",   
         "CEN_OUT_MEALS"."CCUSTOMER_TEXT",   
         "CEN_OUT_MEALS"."NQUANTITY_RECALC",   
         "CEN_OUT_MEALS"."NSALES_PRICE_RECALC",   
         "CEN_OUT_MEALS"."NBILLING_PRICE_RECALC",   
         "CEN_OUT_MEALS"."NCOST_PRICE_RECALC",   
         "CEN_OUT_MEALS"."NREMITTENCEPRICE_RECALC",   
         "CEN_OUT_MEALS"."NVAT_VALUE_RECALC",   
         "CEN_OUT_MEALS"."NDISCOUNT_RECALC",   
         "CEN_OUT_MEALS"."NPORTFEE_RECALC",   
         "CEN_OUT_MEALS"."NCALC_BASIS_RECALC",   
         "CEN_OUT_MEALS"."NIMPORT_FROM_BOB",   
         "CEN_OUT_MEALS"."NVAT_VALUE_PORTFEE",   
         "CEN_OUT_MEALS"."NVAT_KEY",   
         "CEN_OUT_MEALS"."NVAT_KEY_PORTFEE",   
         "CEN_PICTURES"."NPICTURE_INDEX_KEY",   
         "CEN_PACKINGLISTS"."CTEXT_SHORT"  
    FROM "CEN_OUT_MEALS",   
         "CEN_PACKINGLIST_PICTURES",   
         "CEN_PICTURES",   
         "CEN_PACKINGLISTS"  
   WHERE ( cen_out_meals.npackinglist_index_key = cen_packinglist_pictures.npackinglist_index_key (+)) and  
         ( cen_out_meals.npackinglist_detail_key = cen_packinglist_pictures.npackinglist_detail_key (+)) and  
         ( cen_packinglist_pictures.npicture_index_key = cen_pictures.npicture_index_key (+)) and  
         ( "CEN_OUT_MEALS"."NPACKINGLIST_INDEX_KEY" = "CEN_PACKINGLISTS"."NPACKINGLIST_INDEX_KEY" ) and  
         ( "CEN_OUT_MEALS"."NPACKINGLIST_DETAIL_KEY" = "CEN_PACKINGLISTS"."NPACKINGLIST_DETAIL_KEY" ) and  
         ( ( cen_out_meals.nresult_key = :arg_result_key ) AND  
         ( cen_out_meals.nmodule_type = :arg_module ) ) AND
         ( cen_out_meals.cclass = :arg_class OR :arg_class = '-1') AND
         ( cen_out_meals.nbilling_status in (0,1))
         
ORDER BY "CEN_OUT_MEALS"."NCLASS_NUMBER" ASC,   
         "CEN_OUT_MEALS"."NCOVER_PRIO" ASC,   
         "CEN_OUT_MEALS"."NPRIO" ASC   