select tab_pl.npackinglist_index_key,
		tab_pl.npackinglist_detail_key,
		tab_pl.cpackinglist	,
		tab_pl.nlevel,
		tab_pl.npackinglist_key,
		tab_pl.clevel,
		tab_pl.ctype,
		tab_pl.nsort,
		tab_pl.nquantity,
		tab_pl.cunit,
		tab_pl.nquantity_cal,
		tab_pl.nreckoning,
		tab_pl.nworkstation_key,
		tab_pl.narea_key,
		tab_pl.ctext,
		tab_pl.ccustomer_pl,
		tab_pl.ccustomer_text	,
		tab_pl.nreserve,
		tab_pl.npercent,
		tab_pl.nancestor_pl_index_key,
		tab_pl.nancestor_pl_detail_key,
		tab_pl.nmaster_index_key,
		tab_pl.npl_kind_key,
		tab_pl.npl_type_key,
		tab_pl.nmaterial_index_key,
		tab_pl.npicture_index_key,
		tab_pl.ntext_flag,
		tab_pl.cadd_on_text,
		tab_pl.ctext_pl_prod_label,
		cen_packinglists.ctext_short
from table (CBASE_GENERAL.PF_EXPLODE_PACKINGLIST_5_UNIT (	:arg_index,
															:arg_date,
															:arg_include_self,
															:arg_csc,
															:arg_quantity,
															:arg_billing_only,
															:arg_reckoning,
															:arg_time)) tab_pl,
			cen_packinglists
where  tab_pl.npackinglist_index_key = cen_packinglists.npackinglist_index_key and
		tab_pl.npackinglist_detail_key = cen_packinglists.npackinglist_detail_key and
		trim(cpackinglist) <> 'Z'
