SELECT DISTINCT 
	CEN_AIRLINE_ACCOUNTS.CACCOUNT               	  AS  CEN_AIR_CACCOUNT                ,
	CEN_GALLEY.CGALLEY                          	  AS  CEN_GAL_CGALLEY                 ,
	CEN_GALLEY.NSORT                                  AS  CEN_GAL_NSORT                   ,
    CEN_LOADINGLIST_INDEX.CLOADINGLIST          	  AS  CEN_LL_IDX_CLOADINGLIST         ,
	CEN_LOADINGLIST_INDEX.NLOADINGLIST_KEY      	  AS  CEN_LL_IDX_NLOADINGLIST_KEY     ,
	CEN_LOADINGLISTS.CACTIONCODE                	  AS  CEN_LL_CACTIONCODE              ,
	CEN_LOADINGLISTS.CADD_ON_TEXT               	  AS  CEN_LL_CADD_ON_TEXT             ,
	COALESCE(CEN_LOADINGLISTS.CCLASS, ' ')              	  AS  CEN_LL_CCLASS                   ,
	CEN_LOADINGLISTS.CGOODS_RECIPIENT           	  AS  CEN_LL_CGOODS_RECIPIENT         ,
	COALESCE(CEN_LOADINGLISTS.CSALES_REL, ' ')             AS  CEN_LL_CSALES_REL               ,
	CEN_LOADINGLISTS.NBELLY_CONTAINER           	  AS  CEN_LL_NBELLY_CONTAINER         ,
	CEN_LOADINGLISTS.NLOADINGLIST_DETAIL_KEY          AS  CEN_LL_NLOADINGLIST_DETAIL_KEY  ,
	CEN_LOADINGLISTS.NLOADINGLIST_INDEX_KEY           AS  CEN_LL_NLOADINGLIST_INDEX_KEY   ,
	CEN_LOADINGLISTS.NQUANTITY                  	  AS  CEN_LL_NQUANTITY                ,
	COALESCE(CEN_LOADINGLISTS.NRECKONING, 0)            	  AS  CEN_LL_NRECKONING               ,
	CEN_PACKINGLIST_INDEX.CPACKINGLIST          	  AS  CEN_PL_IDX_CPACKINGLIST         ,
	CEN_PACKINGLIST_INDEX.NPACKINGLIST_INDEX_KEY      AS  CEN_PL_IDX_NPL_INDEX_KEY        ,
	CEN_PACKINGLIST_INDEX.NPL_KIND_KEY          	  AS  CEN_PL_IDX_NPL_KIND_KEY         ,
	CEN_PACKINGLISTS.CCUSTOMER_PL               	  AS  CEN_PL_CCUSTOMER_PL             ,
	CEN_PACKINGLISTS.CCUSTOMER_TEXT             	  AS  CEN_PL_CCUSTOMER_TEXT           ,
	COALESCE(CEN_PACKINGLISTS.CDEF_STORAGE_LOCATION, ' ')  AS  CEN_PL_CDEF_STORAGE_LOCATION    ,
	CEN_PACKINGLISTS.CTEXT                      	  AS  CEN_PL_CTEXT                    ,
	CEN_PACKINGLISTS.CTEXT_SHORT                	  AS  CEN_PL_CTEXT_SHORT              ,
	CEN_PACKINGLISTS.CUNIT                      	  AS  CEN_PL_CUNIT                    ,
	CEN_PACKINGLISTS.NACCOUNT_KEY               	  AS  CEN_PL_NACCOUNT_KEY             ,
	CEN_PACKINGLISTS.NPACKINGLIST_DETAIL_KEY    	  AS  CEN_PL_NPACKINGLIST_DETAIL_KEY  ,
	CEN_PACKINGLISTS.NPACKINGLIST_KEY                 AS  CEN_PL_NPACKINGLIST_KEY         ,
	CEN_STOWAGE.CPLACE                          	  AS  CEN_STOW_CPLACE                 ,
	CEN_STOWAGE.CSTOWAGE							  AS  CEN_STOW_CSTOWAGE               ,
	CEN_STOWAGE.NPAGE                           	  AS  CEN_STOW_NPAGE                  ,
	CEN_STOWAGE.NSTOWAGE_KEY                    	  AS  CEN_STOW_NSTOWAGE_KEY           ,
	CEN_STOWAGE.NSORT                                 AS  CEN_STOW_NSORT                  ,
	SYS_PRODUCT_CATEGORY.CTEXT					      AS  SYS_PROD_CPROD_CAT_TEXT         ,
	' '                                               AS  COMPUTE_ONLOAD_TEXT
FROM CEN_LOADINGLISTS
	JOIN CEN_LOADINGLIST_INDEX ON CEN_LOADINGLIST_INDEX.NLOADINGLIST_INDEX_KEY = CEN_LOADINGLISTS.NLOADINGLIST_INDEX_KEY
	JOIN CEN_OUT_HANDLING ON CEN_OUT_HANDLING.CLOADINGLIST = CEN_LOADINGLIST_INDEX.CLOADINGLIST
	JOIN CEN_PACKINGLIST_INDEX ON CEN_PACKINGLIST_INDEX.NPACKINGLIST_INDEX_KEY = CEN_LOADINGLISTS.NPACKINGLIST_INDEX_KEY
	JOIN CEN_PACKINGLISTS ON CEN_PACKINGLISTS.NPACKINGLIST_INDEX_KEY = CEN_PACKINGLIST_INDEX.NPACKINGLIST_INDEX_KEY
	LEFT JOIN CEN_AIRLINE_ACCOUNTS ON CEN_AIRLINE_ACCOUNTS.NACCOUNT_KEY = CEN_PACKINGLISTS.NACCOUNT_KEY
	JOIN CEN_STOWAGE ON CEN_STOWAGE.NSTOWAGE_KEY = CEN_LOADINGLISTS.NSTOWAGE_KEY
	JOIN CEN_GALLEY ON CEN_GALLEY.NGALLEY_KEY = CEN_STOWAGE.NGALLEY_KEY
	LEFT JOIN SYS_PRODUCT_CATEGORY ON SYS_PRODUCT_CATEGORY.CSAP_CODE = CEN_PACKINGLISTS.CPROD_CAT
WHERE :arg_reference_date BETWEEN CEN_LOADINGLIST_INDEX.DVALID_FROM AND CEN_LOADINGLIST_INDEX.DVALID_TO
	AND CEN_OUT_HANDLING.NRESULT_KEY = :arg_result_key AND CEN_OUT_HANDLING.NHANDLING_ID = :arg_handling_id
	AND :arg_reference_date BETWEEN CEN_PACKINGLISTS.DVALID_FROM AND CEN_PACKINGLISTS.DVALID_TO
	AND :arg_reference_time BETWEEN CEN_LOADINGLISTS.CTIME_FROM AND CEN_LOADINGLISTS.CTIME_TO
	AND CEN_LOADINGLISTS.CFREQUENCY LIKE CONCAT('%', DATE_FORMAT(DATE(:arg_reference_date), '%e'), '%')
	AND CEN_LOADINGLISTS.CACTIONCODE <> 'C'
	AND NOT EXISTS (SELECT NEXCLUDE_KEY
				FROM LOC_UNIT_LL_EXCLUDE EX
				WHERE :arg_ll_exclude = '1'
					AND EX.CUNIT = :arg_unit
					AND EX.CLOADINGLIST = CEN_OUT_HANDLING.CLOADINGLIST
					AND :arg_reference_date BETWEEN DVALID_FROM AND DVALID_TO)
ORDER BY CEN_GALLEY.NSORT ASC, CEN_STOWAGE.NSORT ASC