SELECT 
	PLSDETAIL.NPACKINGLIST_INDEX_KEY,
    PLSDETAIL.NDETAIL_KEY,
    PLSTYPE.NPACKINGLIST_KEY,
    PLSTYPE.CTEXT,
    PLSKIND.CKIND,
    PLSKIND.NUSE_RESERVE,
    PLSB.NPACKING_LIST_LEVEL,
    PLSB.NPACKINGLIST_DETAIL_KEY,
    PLSB.CUNIT,
    PLSB.CTEXT AS CPL_TEXT,
    PLSB.CTEXT_SHORT AS CPL_TEXT_SHORT,
    PLSB.CTEXT_SHORT2 AS CPL_TEXT_SHORT2,
    PLSB.CCUSTOMER_PL,
    PLSB.CCUSTOMER_TEXT,
    PLSB.CDEF_STORAGE_LOCATION,
    PLSDETAIL.NRECKONING,
    PLSDETAIL.NNUMBER_PACKAGES,
    PLSDETAIL.NQUANTITY,
    PLSDETAIL.CSALES_REL,
    PLSDETAIL.CGOODS_RECIPIENT,
    PLSIDX.CPACKINGLIST,
    PLSIDX.NPL_KIND_KEY,
    PLSMAT.NMATERIAL_INDEX_KEY,
    PLAREA.NWORKSTATION_KEY,
    PLAREA.NAREA_KEY,
    PLAREA.NPL_AREA_KEY,
    AIRACC.CACCOUNT,
    AIRACC.NACCOUNT_KEY,
    PLTF.NPLTIMEFRAME_INDEX,
    PLTF.NBATCH,
    PLTF.NOFFSET,
    PLTF.NWORKSCHEDULE_INDEX,
    PLTFFLIGHT.NOFFSET NFLIGHT_OFFSET,
    PLTFFLIGHT.NWORKSCHEDULE_INDEX AS NFLIGHT_WORKSCHEDULE_INDEX,
    PLTFFLIGHT.NPLTF_FLIGHT_INDEX_GROUP,
    PLTFFLIGHT.NPLTF_FLIGHT_INDEX,
    PRODCAT.CTEXT AS CPROD_CAT_TEXT
FROM CEN_PACKINGLIST_DETAIL PLSDETAIL
    JOIN CEN_PACKINGLIST_INDEX PLSIDX ON PLSIDX.NPACKINGLIST_INDEX_KEY = PLSDETAIL.NDETAIL_KEY
    JOIN CEN_PACKINGLISTS PLSA ON PLSA.NPACKINGLIST_INDEX_KEY = PLSDETAIL.NPACKINGLIST_INDEX_KEY AND PLSA.NPACKINGLIST_DETAIL_KEY = PLSDETAIL.NPACKINGLIST_DETAIL_KEY AND :arg_date BETWEEN PLSA.DVALID_FROM AND PLSA.DVALID_TO
    JOIN CEN_PACKINGLISTS PLSB ON PLSB.NPACKINGLIST_INDEX_KEY = PLSDETAIL.NDETAIL_KEY AND :arg_date BETWEEN PLSB.DVALID_FROM AND PLSB.DVALID_TO
    JOIN CEN_PACKINGLIST_TYPES PLSTYPE ON PLSTYPE.NPACKINGLIST_KEY = PLSB.NPACKINGLIST_KEY
    JOIN SYS_PACKINGLIST_KINDS PLSKIND ON PLSKIND.NPL_KIND_KEY = PLSIDX.NPL_KIND_KEY
    LEFT JOIN SYS_PRODUCT_CATEGORY PRODCAT ON PRODCAT.CSAP_CODE = PLSB.CPROD_CAT
    LEFT JOIN CEN_PACKINGLIST_MATERIAL PLSMAT ON PLSMAT.NPACKINGLIST_INDEX_KEY = PLSB.NPACKINGLIST_INDEX_KEY AND PLSMAT.NPACKINGLIST_DETAIL_KEY = PLSB.NPACKINGLIST_DETAIL_KEY
    LEFT JOIN LOC_UNIT_PL_AREAS PLAREA ON PLAREA.NPACKINGLIST_INDEX_KEY = PLSB.NPACKINGLIST_INDEX_KEY AND PLAREA.CUNIT = :arg_csc AND :arg_date BETWEEN PLAREA.DVALID_FROM AND PLAREA.DVALID_TO   
    LEFT JOIN CEN_AIRLINE_ACCOUNTS AIRACC ON AIRACC.NACCOUNT_KEY = PLSB.NACCOUNT_KEY
    LEFT JOIN (
        SELECT 
            PLTF.NPACKINGLIST_INDEX_KEY, 
            PLTF.NPLTIMEFRAME_INDEX,
            PLTF.NBATCH,
            PLTF.NOFFSET,
            PLTF.NWORKSCHEDULE_INDEX  
        FROM LOC_PL_TIME_FRAME PLTF
            JOIN LOC_PL_TIME_FRAME_VARIANT PLTFVAR ON PLTFVAR.NVARIANT_INDEX = PLTF.NVARIANT 
            JOIN LOC_UNIT_PPM_VALIDITIES PPMVAL ON PPMVAL.NVALID_INDEX =  PLTFVAR.NVALID_INDEX
            JOIN LOC_UNIT_PROD_TIME_FRAME PRODTF ON PRODTF.NPRODTIMEFRAME_INDEX = PLTF.NPRODTIMEFRAME_INDEX AND PRODTF.NVALID_INDEX = PPMVAL.NVALID_INDEX 
        WHERE 
            ((:arg_check_boarding_unit = 1 AND PPMVAL.CUNIT = PLTF.CUNIT AND :arg_csc IN (PLTF.CUNIT, PLTF.CBOARDING_UNIT))
            	OR (:arg_check_boarding_unit <> 1 AND PPMVAL.CUNIT = :arg_csc))
            AND DATE(:arg_calc_date) - INTERVAL(0, 0, 0, PLTF.NOFFSET) BETWEEN PPMVAL.DVALID_FROM AND PPMVAL.DVALID_TO
            AND :arg_calc_time between PRODTF.CTIMEFROM AND PRODTF.CTIMETO
            AND PRODTF.NAIRLINE_KEY = :arg_airline_key 
            AND PLTFVAR.CFREQUENCY LIKE CONCAT('%', DATE_FORMAT(DATE(:arg_calc_date) - INTERVAL(0, 0, 0, :arg_iso_offset - PLTF.NOFFSET), '%e'), '%')
    ) PLTF ON PLTF.NPACKINGLIST_INDEX_KEY = PLSB.NPACKINGLIST_INDEX_KEY
    LEFT JOIN (
        SELECT 
            PLTFFLIGHT.NPACKINGLIST_INDEX_KEY, 
            PLTFFLIGHT.NWORKSCHEDULE_INDEX,   
            PLTFFLIGHT.NOFFSET,
            PLTFFLIGHT.NPLTF_FLIGHT_INDEX_GROUP,
            PLTFFLIGHT.NPLTF_FLIGHT_INDEX
        FROM LOC_PL_TIME_FRAME_FLIGHT PLTFFLIGHT
            JOIN LOC_UNIT_PPM_VALIDITIES PPMVAL ON PPMVAL.NVALID_INDEX = PLTFFLIGHT.NVALID_INDEX
            JOIN CEN_OUT CO ON CO.CAIRLINE = PLTFFLIGHT.CAIRLINE AND CO.NFLIGHT_NUMBER = PLTFFLIGHT.NFLIGHT_NUMBER 
                AND CO.CSUFFIX = PLTFFLIGHT.CSUFFIX AND CO.CTLC_FROM = PLTFFLIGHT.CTLC_FROM AND CO.CTLC_TO = PLTFFLIGHT.CTLC_TO 
                AND ((:arg_check_boarding_unit = 1 AND CO.CUNIT IN (PLTFFLIGHT.CUNIT, PLTFFLIGHT.CBOARDING_UNIT))
                	OR (:arg_check_boarding_unit <> 1 AND CO.CUNIT = PLTFFLIGHT.CUNIT))
        WHERE DATE(:arg_calc_date) - INTERVAL(0, 0, 0, PLTFFLIGHT.NOFFSET) BETWEEN PPMVAL.DVALID_FROM AND PPMVAL.DVALID_TO
            AND PLTFFLIGHT.NFREQ = CAST(DATE_FORMAT(DATE(CO.DDEPARTURE) - INTERVAL(0, 0, 0, :arg_iso_offset), '%e') AS INTEGER)
            AND CO.NRESULT_KEY = :arg_result_key
    ) PLTFFLIGHT ON PLTFFLIGHT.NPACKINGLIST_INDEX_KEY = PLSB.NPACKINGLIST_INDEX_KEY
WHERE PLSDETAIL.NPACKINGLIST_INDEX_KEY IN (:arg_index)
    AND :arg_date between PLSDETAIL.DVALID_FROM AND PLSDETAIL.DVALID_TO
    AND PLSB.NPACKING_LIST_LEVEL <> 3
    AND PLSIDX.CPACKINGLIST NOT LIKE 'Z%'
ORDER BY PLSDETAIL.NPACKINGLIST_INDEX_KEY, PLSDETAIL.NSORT ASC