package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 29.03.2016 13:08:37 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAirlCategoriesId generated by hbm2java
 */
@Embeddable
public class CenAirlCategoriesId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long ncatKey;
	private long nairlineKey;

	@Column(name = "NCAT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcatKey() {
		return this.ncatKey;
	}

	public void setNcatKey(final long ncatKey) {
		this.ncatKey = ncatKey;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenAirlCategoriesId)) {
			return false;
		}
		final CenAirlCategoriesId castOther = (CenAirlCategoriesId) other;

		return this.getNcatKey() == castOther.getNcatKey()
				&& this.getNairlineKey() == castOther.getNairlineKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNcatKey();
		result = 37 * result + (int) this.getNairlineKey();
		return result;
	}

}
