package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 22.12.2021 12:22:25 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAirlineLogosId generated by hbm2java
 */
@Embeddable
public class CenAirlineLogosId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nairlineKey;
     private int ntyp;

    public CenAirlineLogosId() {
    }

    public CenAirlineLogosId(long nairlineKey, int ntyp) {
       this.nairlineKey = nairlineKey;
       this.ntyp = ntyp;
    }
   


    @Column(name="NAIRLINE_KEY", nullable=false, precision=12, scale=0)
    public long getNairlineKey() {
        return this.nairlineKey;
    }
    
    public void setNairlineKey(long nairlineKey) {
        this.nairlineKey = nairlineKey;
    }


    @Column(name="NTYP", nullable=false, precision=1, scale=0)
    public int getNtyp() {
        return this.ntyp;
    }
    
    public void setNtyp(int ntyp) {
        this.ntyp = ntyp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenAirlineLogosId) ) return false;
		 CenAirlineLogosId castOther = ( CenAirlineLogosId ) other; 
         
		 return (this.getNairlineKey()==castOther.getNairlineKey())
 && (this.getNtyp()==castOther.getNtyp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNairlineKey();
         result = 37 * result + this.getNtyp();
         return result;
   }   


}


