package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.06.2016 14:43:50 by Hibernate Tools 4.3.2-SNAPSHOT

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAircraftRegistrationsId generated by hbm2java
 */
@Embeddable
public class CenAircraftRegistrationsId extends AbstractDomainObjectPK implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long naircraftKey;
	private String cregistration;

	public CenAircraftRegistrationsId() {
	}

	public CenAircraftRegistrationsId(final long naircraftKey, final String cregistration) {
		this.naircraftKey = naircraftKey;
		this.cregistration = cregistration;
	}

	@Column(name = "NAIRCRAFT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNaircraftKey() {
		return this.naircraftKey;
	}

	public void setNaircraftKey(final long naircraftKey) {
		this.naircraftKey = naircraftKey;
	}

	@Column(name = "CREGISTRATION", nullable = false, length = 10)
	public String getCregistration() {
		return this.cregistration;
	}

	public void setCregistration(final String cregistration) {
		this.cregistration = cregistration;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenAircraftRegistrationsId)) {
			return false;
		}
		final CenAircraftRegistrationsId castOther = (CenAircraftRegistrationsId) other;

		return this.getNaircraftKey() == castOther.getNaircraftKey()
				&& (this.getCregistration() == castOther.getCregistration() || this.getCregistration() != null
						&& castOther.getCregistration() != null && this.getCregistration().equals(castOther.getCregistration()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNaircraftKey();
		result = 37 * result + (getCregistration() == null ? 0 : this.getCregistration().hashCode());
		return result;
	}

}
