package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Apr 3, 2025 9:40:21 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAirlFlagsValuesId generated by hbm2java
 */
@Embeddable
public class CenAirlFlagsValuesId implements java.io.Serializable {

    private long nflagId;
    private long nairlineKey;
    private long nplKindKey;
    private String cflagvalue;

    @Column(name = "NFLAG_ID", nullable = false, precision = 12, scale = 0)
    public long getNflagId() {
        return this.nflagId;
    }

    public void setNflagId(long nflagId) {
        this.nflagId = nflagId;
    }

    @Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
    public long getNairlineKey() {
        return this.nairlineKey;
    }

    public void setNairlineKey(long nairlineKey) {
        this.nairlineKey = nairlineKey;
    }

    @Column(name = "NPL_KIND_KEY", nullable = false, precision = 12, scale = 0)
    public long getNplKindKey() {
        return this.nplKindKey;
    }

    public void setNplKindKey(long nplKindKey) {
        this.nplKindKey = nplKindKey;
    }

    @Column(name = "CFLAGVALUE", nullable = false, length = 40)
    public String getCflagvalue() {
        return this.cflagvalue;
    }

    public void setCflagvalue(String cflagvalue) {
        this.cflagvalue = cflagvalue;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CenAirlFlagsValuesId))
            return false;
        CenAirlFlagsValuesId castOther = (CenAirlFlagsValuesId) other;

        return (this.getNflagId() == castOther.getNflagId())
                && (this.getNairlineKey() == castOther.getNairlineKey())
                && (this.getNplKindKey() == castOther.getNplKindKey())
                && ((this.getCflagvalue() == castOther.getCflagvalue()) || (this.getCflagvalue() != null && castOther.getCflagvalue() != null && this.getCflagvalue()
                .equals(castOther.getCflagvalue())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getNflagId();
        result = 37 * result + (int) this.getNairlineKey();
        result = 37 * result + (int) this.getNplKindKey();
        result = 37 * result + (getCflagvalue() == null ? 0 : this.getCflagvalue().hashCode());
        return result;
    }

}


