package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 22.03.2019 13:07:37 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAppSetupId generated by hbm2java
 */
@Embeddable
public class CenAppSetupId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String capp;
	private String csection;
	private String ckey;

	public CenAppSetupId() {
	}

	public CenAppSetupId(final String capp, final String csection, final String ckey) {
		this.capp = capp;
		this.csection = csection;
		this.ckey = ckey;
	}

	@Column(name = "CAPP", nullable = false, length = 40)
	public String getCapp() {
		return this.capp;
	}

	public void setCapp(final String capp) {
		this.capp = capp;
	}

	@Column(name = "CSECTION", nullable = false, length = 25)
	public String getCsection() {
		return this.csection;
	}

	public void setCsection(final String csection) {
		this.csection = csection;
	}

	@Column(name = "CKEY", nullable = false, length = 25)
	public String getCkey() {
		return this.ckey;
	}

	public void setCkey(final String ckey) {
		this.ckey = ckey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenAppSetupId)) {
			return false;
		}
		final CenAppSetupId castOther = (CenAppSetupId) other;

		return ((this.getCapp() == castOther.getCapp())
				|| (this.getCapp() != null && castOther.getCapp() != null && this.getCapp().equals(castOther.getCapp())))
				&& ((this.getCsection() == castOther.getCsection()) || (this.getCsection() != null && castOther.getCsection() != null
						&& this.getCsection().equals(castOther.getCsection())))
				&& ((this.getCkey() == castOther.getCkey())
						|| (this.getCkey() != null && castOther.getCkey() != null && this.getCkey().equals(castOther.getCkey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCapp() == null ? 0 : this.getCapp().hashCode());
		result = 37 * result + (getCsection() == null ? 0 : this.getCsection().hashCode());
		result = 37 * result + (getCkey() == null ? 0 : this.getCkey().hashCode());
		return result;
	}

}
