package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 12.05.2016 08:27:40 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAirlineUnitId generated by hbm2java
 */
@Embeddable
public class CenAirlineUnitId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nairlineKey;
	private String cunit;

	public CenAirlineUnitId() {
	}

	public CenAirlineUnitId(final long nairlineKey, final String cunit) {
		this.nairlineKey = nairlineKey;
		this.cunit = cunit;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenAirlineUnitId)) {
			return false;
		}
		final CenAirlineUnitId castOther = (CenAirlineUnitId) other;

		return this.getNairlineKey() == castOther.getNairlineKey()
				&& (this.getCunit() == castOther.getCunit()
						|| this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNairlineKey();
		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		return result;
	}

}
