package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Mar 17, 2025 12:31:04 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenAirlFlagsId generated by hbm2java
 */
@Embeddable
public class CenAirlFlagsId  implements java.io.Serializable {


     private long nflagId;
     private long nairlineKey;
     private long nplKindKey;

    @Column(name="NFLAG_ID", nullable=false, precision=12, scale=0)
    public long getNflagId() {
        return this.nflagId;
    }
    
    public void setNflagId(long nflagId) {
        this.nflagId = nflagId;
    }


    @Column(name="NAIRLINE_KEY", nullable=false, precision=12, scale=0)
    public long getNairlineKey() {
        return this.nairlineKey;
    }
    
    public void setNairlineKey(long nairlineKey) {
        this.nairlineKey = nairlineKey;
    }


    @Column(name="NPL_KIND_KEY", nullable=false, precision=12, scale=0)
    public long getNplKindKey() {
        return this.nplKindKey;
    }
    
    public void setNplKindKey(long nplKindKey) {
        this.nplKindKey = nplKindKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenAirlFlagsId) ) return false;
		 CenAirlFlagsId castOther = ( CenAirlFlagsId ) other; 
         
		 return (this.getNflagId()==castOther.getNflagId())
 && (this.getNairlineKey()==castOther.getNairlineKey())
 && (this.getNplKindKey()==castOther.getNplKindKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNflagId();
         result = 37 * result + (int) this.getNairlineKey();
         result = 37 * result + (int) this.getNplKindKey();
         return result;
   }   


}


