package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 22.08.2016 17:41:45 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenCateringUoPdfId generated by hbm2java
 */
@Embeddable
public class CenCateringUoPdfId implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long ncateringUserobjectId;
	private Date dvalidFrom;

	public CenCateringUoPdfId() {
	}

	public CenCateringUoPdfId(final long ncateringUserobjectId, final Date dvalidFrom) {
		this.ncateringUserobjectId = ncateringUserobjectId;
		this.dvalidFrom = dvalidFrom;
	}

	@Column(name = "NCATERING_USEROBJECT_ID", nullable = false, precision = 12, scale = 0)
	public long getNcateringUserobjectId() {
		return this.ncateringUserobjectId;
	}

	public void setNcateringUserobjectId(final long ncateringUserobjectId) {
		this.ncateringUserobjectId = ncateringUserobjectId;
	}

	@Column(name = "DVALID_FROM", nullable = false, length = 7)
	public Date getDvalidFrom() {
		return this.dvalidFrom;
	}

	public void setDvalidFrom(final Date dvalidFrom) {
		this.dvalidFrom = dvalidFrom;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenCateringUoPdfId)) {
			return false;
		}
		final CenCateringUoPdfId castOther = (CenCateringUoPdfId) other;

		return this.getNcateringUserobjectId() == castOther.getNcateringUserobjectId()
				&& (this.getDvalidFrom() == castOther.getDvalidFrom() || this.getDvalidFrom() != null
						&& castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNcateringUserobjectId();
		result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
		return result;
	}

}
