package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 13.04.2022 09:24:43 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenCostSnapPlSumId generated by hbm2java
 */
@Embeddable
public class CenCostSnapPlSumId  implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long npackinglistIndexKey;
     private long npackinglistDetailKey;
     private String cunit;
     private long npriceCatKey;

    public CenCostSnapPlSumId() {
    }

    public CenCostSnapPlSumId(long npackinglistIndexKey, long npackinglistDetailKey, String cunit, long npriceCatKey) {
       this.npackinglistIndexKey = npackinglistIndexKey;
       this.npackinglistDetailKey = npackinglistDetailKey;
       this.cunit = cunit;
       this.npriceCatKey = npriceCatKey;
    }
   


    @Column(name="NPACKINGLIST_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistIndexKey() {
        return this.npackinglistIndexKey;
    }
    
    public void setNpackinglistIndexKey(long npackinglistIndexKey) {
        this.npackinglistIndexKey = npackinglistIndexKey;
    }


    @Column(name="NPACKINGLIST_DETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistDetailKey() {
        return this.npackinglistDetailKey;
    }
    
    public void setNpackinglistDetailKey(long npackinglistDetailKey) {
        this.npackinglistDetailKey = npackinglistDetailKey;
    }


    @Column(name="CUNIT", nullable=false, length=5)
    public String getCunit() {
        return this.cunit;
    }
    
    public void setCunit(String cunit) {
        this.cunit = cunit;
    }


    @Column(name="NPRICE_CAT_KEY", nullable=false, precision=12, scale=0)
    public long getNpriceCatKey() {
        return this.npriceCatKey;
    }
    
    public void setNpriceCatKey(long npriceCatKey) {
        this.npriceCatKey = npriceCatKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenCostSnapPlSumId) ) return false;
		 CenCostSnapPlSumId castOther = ( CenCostSnapPlSumId ) other; 
         
		 return (this.getNpackinglistIndexKey()==castOther.getNpackinglistIndexKey())
 && (this.getNpackinglistDetailKey()==castOther.getNpackinglistDetailKey())
 && ( (this.getCunit()==castOther.getCunit()) || ( this.getCunit()!=null && castOther.getCunit()!=null && this.getCunit().equals(castOther.getCunit()) ) )
 && (this.getNpriceCatKey()==castOther.getNpriceCatKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNpackinglistIndexKey();
         result = 37 * result + (int) this.getNpackinglistDetailKey();
         result = 37 * result + ( getCunit() == null ? 0 : this.getCunit().hashCode() );
         result = 37 * result + (int) this.getNpriceCatKey();
         return result;
   }   


}


