package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 07.06.2016 15:04:48 by Hibernate Tools 4.3.2-SNAPSHOT

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenClassNameId generated by hbm2java
 */
@Embeddable
public class CenClassNameId extends AbstractDomainObjectPK implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nairlineKey;
	private String cclass;

	public CenClassNameId() {
	}

	public CenClassNameId(final long nairlineKey, final String cclass) {
		this.nairlineKey = nairlineKey;
		this.cclass = cclass;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Column(name = "CCLASS", nullable = false, length = 10)
	public String getCclass() {
		return this.cclass;
	}

	public void setCclass(final String cclass) {
		this.cclass = cclass;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenClassNameId)) {
			return false;
		}
		final CenClassNameId castOther = (CenClassNameId) other;

		return this.getNairlineKey() == castOther.getNairlineKey()
				&& (this.getCclass() == castOther.getCclass()
						|| this.getCclass() != null && castOther.getCclass() != null && this.getCclass().equals(castOther.getCclass()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNairlineKey();
		result = 37 * result + (getCclass() == null ? 0 : this.getCclass().hashCode());
		return result;
	}

}
