package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 25.06.2021 11:44:31 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenDynReportRowsId generated by hbm2java
 */
@Embeddable
public class CenDynReportRowsId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nrequestKey;
	private int nrow;
	private String ccolumn;

	public CenDynReportRowsId() {
	}

	public CenDynReportRowsId(final long nrequestKey, final int nrow, final String ccolumn) {
		this.nrequestKey = nrequestKey;
		this.nrow = nrow;
		this.ccolumn = ccolumn.substring(Math.max(0, ccolumn.length() - 32));
	}

	@Column(name = "NREQUEST_KEY", nullable = false, precision = 12, scale = 0)
	public long getNrequestKey() {
		return this.nrequestKey;
	}

	public void setNrequestKey(long nrequestKey) {
		this.nrequestKey = nrequestKey;
	}

	@Column(name = "NROW", nullable = false, precision = 4, scale = 0)
	public int getNrow() {
		return this.nrow;
	}

	public void setNrow(int nrow) {
		this.nrow = nrow;
	}

	@Column(name = "CCOLUMN", nullable = false, length = 32)
	public String getCcolumn() {
		return this.ccolumn;
	}

	public void setCcolumn(String ccolumn) {
		this.ccolumn = ccolumn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CenDynReportRowsId))
			return false;
		CenDynReportRowsId castOther = (CenDynReportRowsId) other;

		return (this.getNrequestKey() == castOther.getNrequestKey())
				&& (this.getNrow() == castOther.getNrow())
				&& ((this.getCcolumn() == castOther.getCcolumn()) || (this.getCcolumn() != null && castOther.getCcolumn() != null
				&& this.getCcolumn().equals(castOther.getCcolumn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNrequestKey();
		result = 37 * result + this.getNrow();
		result = 37 * result + (getCcolumn() == null ? 0 : this.getCcolumn().hashCode());
		return result;
	}
}


