package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenEuPicturesId generated by hbm2java
 */
@Embeddable
public class CenEuPicturesId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long neuRegionKey;
	private String cpackinglist;
	private Date dvalidFrom;

	public CenEuPicturesId() {
	}

	public CenEuPicturesId(final long neuRegionKey, final String cpackinglist, final Date dvalidFrom) {
		this.neuRegionKey = neuRegionKey;
		this.cpackinglist = cpackinglist;
		this.dvalidFrom = dvalidFrom;
	}

	@Column(name = "NEU_REGION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNeuRegionKey() {
		return this.neuRegionKey;
	}

	public void setNeuRegionKey(final long neuRegionKey) {
		this.neuRegionKey = neuRegionKey;
	}

	@Column(name = "CPACKINGLIST", nullable = false, length = 18)
	public String getCpackinglist() {
		return this.cpackinglist;
	}

	public void setCpackinglist(final String cpackinglist) {
		this.cpackinglist = cpackinglist;
	}

	@Column(name = "DVALID_FROM", nullable = false, length = 7)
	public Date getDvalidFrom() {
		return this.dvalidFrom;
	}

	public void setDvalidFrom(final Date dvalidFrom) {
		this.dvalidFrom = dvalidFrom;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenEuPicturesId)) {
			return false;
		}
		final CenEuPicturesId castOther = (CenEuPicturesId) other;

		return this.getNeuRegionKey() == castOther.getNeuRegionKey()
				&& (this.getCpackinglist() == castOther.getCpackinglist() || this.getCpackinglist() != null
						&& castOther.getCpackinglist() != null && this.getCpackinglist().equals(castOther.getCpackinglist()))
				&& (this.getDvalidFrom() == castOther.getDvalidFrom() || this.getDvalidFrom() != null
						&& castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNeuRegionKey();
		result = 37 * result + (getCpackinglist() == null ? 0 : this.getCpackinglist().hashCode());
		result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
		return result;
	}

}
