package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 23.06.2016 20:40:32 by Hibernate Tools 4.3.2-SNAPSHOT

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenEuItemsAlgId generated by hbm2java
 */
@Embeddable
public class CenEuItemsAlgId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long neuItemKey;
	private long neuAllgKey;

	public CenEuItemsAlgId() {
	}

	public CenEuItemsAlgId(final long neuItemKey, final long neuAllgKey) {
		this.neuItemKey = neuItemKey;
		this.neuAllgKey = neuAllgKey;
	}

	@Column(name = "NEU_ITEM_KEY", nullable = false, precision = 12, scale = 0)
	public long getNeuItemKey() {
		return this.neuItemKey;
	}

	public void setNeuItemKey(final long neuItemKey) {
		this.neuItemKey = neuItemKey;
	}

	@Column(name = "NEU_ALLG_KEY", nullable = false, precision = 12, scale = 0)
	public long getNeuAllgKey() {
		return this.neuAllgKey;
	}

	public void setNeuAllgKey(final long neuAllgKey) {
		this.neuAllgKey = neuAllgKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenEuItemsAlgId)) {
			return false;
		}
		final CenEuItemsAlgId castOther = (CenEuItemsAlgId) other;

		return this.getNeuItemKey() == castOther.getNeuItemKey()
				&& this.getNeuAllgKey() == castOther.getNeuAllgKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNeuItemKey();
		result = 37 * result + (int) this.getNeuAllgKey();
		return result;
	}

}
