package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 20.05.2016 12:31:08 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenKeyListId generated by hbm2java
 */
@Embeddable
public class CenKeyListId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nsessionKey;
	private long nresultKey;

	public CenKeyListId() {
	}

	public CenKeyListId(final long nsessionKey, final long nresultKey) {
		this.nsessionKey = nsessionKey;
		this.nresultKey = nresultKey;
	}

	@Column(name = "NSESSION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNsessionKey() {
		return this.nsessionKey;
	}

	public void setNsessionKey(final long nsessionKey) {
		this.nsessionKey = nsessionKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenKeyListId)) {
			return false;
		}
		final CenKeyListId castOther = (CenKeyListId) other;

		return this.getNsessionKey() == castOther.getNsessionKey()
				&& this.getNresultKey() == castOther.getNresultKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNsessionKey();
		result = 37 * result + (int) this.getNresultKey();
		return result;
	}

}
