package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 24.05.2016 09:45:22 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenLabelDetailId generated by hbm2java
 */
@Embeddable
public class CenLabelDetailId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nlabelTypeKey;
	private Date dvalidFrom;
	private long nlabelDetailKey;

	public CenLabelDetailId() {
	}

	public CenLabelDetailId(final long nlabelTypeKey, final Date dvalidFrom, final long nlabelDetailKey) {
		this.nlabelTypeKey = nlabelTypeKey;
		this.dvalidFrom = dvalidFrom;
		this.nlabelDetailKey = nlabelDetailKey;
	}

	@Column(name = "NLABEL_TYPE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlabelTypeKey() {
		return this.nlabelTypeKey;
	}

	public void setNlabelTypeKey(final long nlabelTypeKey) {
		this.nlabelTypeKey = nlabelTypeKey;
	}

	@Column(name = "DVALID_FROM", nullable = false, length = 7)
	public Date getDvalidFrom() {
		return this.dvalidFrom;
	}

	public void setDvalidFrom(final Date dvalidFrom) {
		this.dvalidFrom = dvalidFrom;
	}

	@Column(name = "NLABEL_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlabelDetailKey() {
		return this.nlabelDetailKey;
	}

	public void setNlabelDetailKey(final long nlabelDetailKey) {
		this.nlabelDetailKey = nlabelDetailKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenLabelDetailId)) {
			return false;
		}
		final CenLabelDetailId castOther = (CenLabelDetailId) other;

		return this.getNlabelTypeKey() == castOther.getNlabelTypeKey()
				&& (this.getDvalidFrom() == castOther.getDvalidFrom() || this.getDvalidFrom() != null
						&& castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom()))
				&& this.getNlabelDetailKey() == castOther.getNlabelDetailKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNlabelTypeKey();
		result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
		result = 37 * result + (int) this.getNlabelDetailKey();
		return result;
	}

}
