package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jan 23, 2019 2:41:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenMealsPackagesId generated by hbm2java
 */
@Embeddable
public class CenMealsPackagesId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** nhandlingMealKey */
	private long nhandlingMealKey;

	/** nairlinePackagesKey */
	private long nairlinePackagesKey;

	@Column(name = "NHANDLING_MEAL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNhandlingMealKey() {
		return this.nhandlingMealKey;
	}

	public void setNhandlingMealKey(final long nhandlingMealKey) {
		this.nhandlingMealKey = nhandlingMealKey;
	}

	@Column(name = "NAIRLINE_PACKAGES_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlinePackagesKey() {
		return this.nairlinePackagesKey;
	}

	public void setNairlinePackagesKey(final long nairlinePackagesKey) {
		this.nairlinePackagesKey = nairlinePackagesKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenMealsPackagesId)) {
			return false;
		}
		final CenMealsPackagesId castOther = (CenMealsPackagesId) other;

		return (this.getNhandlingMealKey() == castOther.getNhandlingMealKey())
				&& (this.getNairlinePackagesKey() == castOther.getNairlinePackagesKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNhandlingMealKey();
		result = 37 * result + (int) this.getNairlinePackagesKey();
		return result;
	}

}
