package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 09.03.2020 11:40:49 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutCsoShownId generated by hbm2java
 */
@Embeddable
public class CenOutCsoShownId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nresultKey;
     private long nuserId;

    public CenOutCsoShownId() {
    }

    public CenOutCsoShownId(long nresultKey, long nuserId) {
       this.nresultKey = nresultKey;
       this.nuserId = nuserId;
    }
   


    @Column(name="NRESULT_KEY", nullable=false, precision=12, scale=0)
    public long getNresultKey() {
        return this.nresultKey;
    }
    
    public void setNresultKey(long nresultKey) {
        this.nresultKey = nresultKey;
    }


    @Column(name="NUSER_ID", nullable=false, precision=12, scale=0)
    public long getNuserId() {
        return this.nuserId;
    }
    
    public void setNuserId(long nuserId) {
        this.nuserId = nuserId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenOutCsoShownId) ) return false;
		 CenOutCsoShownId castOther = ( CenOutCsoShownId ) other; 
         
		 return (this.getNresultKey()==castOther.getNresultKey())
 && (this.getNuserId()==castOther.getNuserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNresultKey();
         result = 37 * result + (int) this.getNuserId();
         return result;
   }   


}


