package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 22.09.2017 15:32:43 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPpmSchedBreakId generated by hbm2java
 */
@Embeddable
public class CenOutPpmSchedBreakId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nppmSchedKey;
	private long nscheduleBreakKey;

	public CenOutPpmSchedBreakId() {
	}

	public CenOutPpmSchedBreakId(final long nppmSchedKey, final long nscheduleBreakKey) {
		this.nppmSchedKey = nppmSchedKey;
		this.nscheduleBreakKey = nscheduleBreakKey;
	}

	@Column(name = "NPPM_SCHED_KEY", nullable = false, precision = 12, scale = 0)
	public long getNppmSchedKey() {
		return this.nppmSchedKey;
	}

	public void setNppmSchedKey(final long nppmSchedKey) {
		this.nppmSchedKey = nppmSchedKey;
	}

	@Column(name = "NSCHEDULE_BREAK_KEY", nullable = false, precision = 12, scale = 0)
	public long getNscheduleBreakKey() {
		return this.nscheduleBreakKey;
	}

	public void setNscheduleBreakKey(final long nscheduleBreakKey) {
		this.nscheduleBreakKey = nscheduleBreakKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutPpmSchedBreakId)) {
			return false;
		}
		final CenOutPpmSchedBreakId castOther = (CenOutPpmSchedBreakId) other;

		return (this.getNppmSchedKey() == castOther.getNppmSchedKey())
				&& (this.getNscheduleBreakKey() == castOther.getNscheduleBreakKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNppmSchedKey();
		result = 37 * result + (int) this.getNscheduleBreakKey();
		return result;
	}

}
