package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 09.10.2025 10:32:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutQpId generated by hbm2java
 */
@Embeddable
public class CenOutQpId implements java.io.Serializable {

	private long nresultKey;
	private long nairlineQpKey;

	public CenOutQpId() {
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NAIRLINE_QP_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineQpKey() {
		return this.nairlineQpKey;
	}

	public void setNairlineQpKey(long nairlineQpKey) {
		this.nairlineQpKey = nairlineQpKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CenOutQpId))
			return false;
		CenOutQpId castOther = (CenOutQpId) other;

		return (this.getNresultKey() == castOther.getNresultKey())
				&& (this.getNairlineQpKey() == castOther.getNairlineQpKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNairlineQpKey();
		return result;
	}

}


