package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

/**
 * CenOutCheckptId generated by hbm2java
 */
@Embeddable
public class CenOutCheckptId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nresultKey;

	private long ncheckpointKey;

	public CenOutCheckptId() {
	}

	public CenOutCheckptId(final long nresultKey, final long ncheckpointKey) {
		this.nresultKey = nresultKey;
		this.ncheckpointKey = ncheckpointKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NCHECKPOINT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcheckpointKey() {
		return this.ncheckpointKey;
	}

	public void setNcheckpointKey(final long ncheckpointKey) {
		this.ncheckpointKey = ncheckpointKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenOutCheckptId)) {
			return false;
		}
		final CenOutCheckptId castOther = (CenOutCheckptId) other;

		return this.getNresultKey() == castOther.getNresultKey()
				&& this.getNcheckpointKey() == castOther.getNcheckpointKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNcheckpointKey();
		return result;
	}

	/** {@inheritDoc} */
	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this);
	}

	/** {@inheritDoc} */
	@Override
	public String asString() {
		return toString();
	}

}
