package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jan 13, 2020 3:50:45 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPpmLogId generated by hbm2java
 */
@Embeddable
public class CenOutPpmLogId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nlogKey;
	private long nresultKey;
	private long npos;

	public CenOutPpmLogId() {
	}

	/**
	 * @param nlogKey
	 * @param nresultKey
	 * @param npos
	 */
	public CenOutPpmLogId(long nlogKey, long nresultKey, long npos) {
		this.nlogKey = nlogKey;
		this.nresultKey = nresultKey;
		this.npos = npos;
	}

	@Column(name = "NLOG_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlogKey() {
		return this.nlogKey;
	}

	public void setNlogKey(long nlogKey) {
		this.nlogKey = nlogKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NPOS", nullable = false, precision = 12, scale = 0)
	public long getNpos() {
		return this.npos;
	}

	public void setNpos(long npos) {
		this.npos = npos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CenOutPpmLogId))
			return false;
		CenOutPpmLogId castOther = (CenOutPpmLogId) other;

		return (this.getNlogKey() == castOther.getNlogKey())
				&& (this.getNresultKey() == castOther.getNresultKey())
				&& (this.getNpos() == castOther.getNpos());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNlogKey();
		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNpos();
		return result;
	}

}
