package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jan 23, 2019 2:41:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutTextAreaId generated by hbm2java
 */
@Embeddable
public class CenOutTextAreaId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** nresultKey */
	private long nresultKey;

	/** nareaKey */
	private long nareaKey;

	public CenOutTextAreaId() {
	}

	public CenOutTextAreaId(final long nresultKey, final long nareaKey) {
		this.nresultKey = nresultKey;
		this.nareaKey = nareaKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NAREA_KEY", nullable = false, precision = 12, scale = 0)
	public long getNareaKey() {
		return this.nareaKey;
	}

	public void setNareaKey(final long nareaKey) {
		this.nareaKey = nareaKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutTextAreaId)) {
			return false;
		}
		final CenOutTextAreaId castOther = (CenOutTextAreaId) other;

		return (this.getNresultKey() == castOther.getNresultKey())
				&& (this.getNareaKey() == castOther.getNareaKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNareaKey();
		return result;
	}

}
