package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 14.09.2023 07:00:27 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * CenOutPpmBatchV generated by hbm2java
 */
@Entity
// Since it's a view no updated allowed
@Immutable
@Table(name = "CEN_OUT_PPM_BATCH_V")
public class CenOutPpmBatchV implements DomainObject, java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private Long nbatchSeq;
	private String cfirstFlight;
	private Date ddepartureTime;
	private BigDecimal ntype;
	private String cpackinglist;
	private String ctext;
	private String caddOnText;
	private BigDecimal nareaKey;
	private String careaCode;
	private String carea;
	private String cunitOfIssue;
	private BigDecimal nworkstationKey;
	private String cworkstation;
	private String cworkstationText;
	private BigDecimal npackinglistIndexKey;
	private BigDecimal npackinglistDetailKey;
	private BigDecimal nquantity;
	private BigDecimal nheight;
	private BigDecimal nwidth;
	private String cclass;
	private BigDecimal nclassNumber;
	private BigDecimal nplDistributionKey;
	private BigDecimal nprint;
	private String cmealControlCode;
	private BigDecimal nlabelTypeKey;
	private BigDecimal nlabelType;
	private BigDecimal nduplicated;
	private BigDecimal nunitPriority;
	private BigDecimal ncomputeLeg;
	private BigDecimal nseparator;
	private BigDecimal nmodified;
	private BigDecimal ngalleyGroup;
	private Date dprodDate;
	private BigDecimal npltypeKey;
	private String cplType;
	private BigDecimal nlabelCounter;
	private BigDecimal ncomputeNextLeg;
	private BigDecimal nseconds;
	private BigDecimal nphfFlag;
	private BigDecimal nreserve;
	private BigDecimal nquantityProd;
	private BigDecimal nbatchNo;
	private Date dtimeStart;
	private Date dtimeStop;
	private BigDecimal ntempStart;
	private BigDecimal ntempStop;
	private BigDecimal nstatus;
	private BigDecimal nmanualSplit;
	private String cuserStart;
	private String cuserStop;
	private BigDecimal nalertLevel;
	private String cunit;
	private Date dcreatedDate;
	private Date dupdatedDate;
	private String csequence;
	private String cuserDetails;
	private String cverificationUser;
	private Date dverificationDate;
	private String cremarkAction;
	private String cwoDescription;
	private BigDecimal nwoOffset;
	private String cwoTimeFrom;
	private String cwoTimeTo;
	private BigDecimal nmaxBatchSize;
	private BigDecimal nsequence;
	private BigDecimal nempCount;
	private Date dplannedStart;
	private Date dplannedEnd;
	private BigDecimal nduration;
	private Long nworkscheduleIndex;
	private String ctextShort;
	private String cuserStart2;
	private String cuserStart3;
	private String cschedule;
	private Long nppmSchedKey;
	private BigDecimal nroomTemp;
	private BigDecimal ngoldStandard;
	private BigDecimal nmoved;
	private BigDecimal nquantityProdPlanned;
	private BigDecimal ndurationSync;
	private BigDecimal ninsertBySync;
	private BigDecimal ncapacity;
	private String cunitCapacity;
	private BigDecimal nrunrate;
	private BigDecimal nsetuprate;
	private String cuserLock;
	private BigDecimal nppmtrailKey;
	private String ctextLocUnitPlProdLabel;
	private BigDecimal nsectorKey;
	private String csector;
	private BigDecimal nbatchSeqProdLabel;
	private BigDecimal nambientTray;
	private BigDecimal nplKindKey;
	private BigDecimal ngalleyKey;
	private String cgalley;
	private BigDecimal nstowageKey;
	private String cstowage;
	private String cplace;
	private BigDecimal ngalleySort;
	private BigDecimal nstowageSort;
	private BigDecimal nbellyContainer;
	private BigDecimal nchangeOverTime;
	private String cservingUnit;
	private BigDecimal nincreaseLabelsPrinted;
	private BigDecimal npreproduction;
	private BigDecimal nquantityInventory;
	private BigDecimal ntempCookingFinished;
	private Date dtimeCookingFinished;
	private String cuserCookingFinished;
	private BigDecimal nproductSeared;
	private BigDecimal ntempChillingStarted;
	private Date dtimeChillingStarted;
	private BigDecimal ntempChillingFinished;
	private Date dtimeChillingFinished;
	private String cuserChillingFinished;
	private BigDecimal nshortagewastageKey;
	private BigDecimal nquantityVers;

	@Id
	@Column(name = "NBATCH_SEQ", precision = 12, scale = 0)
	public Long getNbatchSeq() {
		return this.nbatchSeq;
	}

	public void setNbatchSeq(Long nbatchSeq) {
		this.nbatchSeq = nbatchSeq;
	}

	@Column(name = "CFIRST_FLIGHT", length = 4000)
	public String getCfirstFlight() {
		return this.cfirstFlight;
	}

	public void setCfirstFlight(String cfirstFlight) {
		this.cfirstFlight = cfirstFlight;
	}

	@Column(name = "DDEPARTURE_TIME", length = 7)
	public Date getDdepartureTime() {
		return this.ddepartureTime;
	}

	public void setDdepartureTime(Date ddepartureTime) {
		this.ddepartureTime = ddepartureTime;
	}

	@Column(name = "NTYPE", precision = 22, scale = 0)
	public BigDecimal getNtype() {
		return this.ntype;
	}

	public void setNtype(BigDecimal ntype) {
		this.ntype = ntype;
	}

	@Column(name = "CPACKINGLIST", length = 40)
	public String getCpackinglist() {
		return this.cpackinglist;
	}

	public void setCpackinglist(String cpackinglist) {
		this.cpackinglist = cpackinglist;
	}

	@Column(name = "CTEXT", length = 256)
	public String getCtext() {
		return this.ctext;
	}

	public void setCtext(String ctext) {
		this.ctext = ctext;
	}

	@Column(name = "CADD_ON_TEXT", length = 80)
	public String getCaddOnText() {
		return this.caddOnText;
	}

	public void setCaddOnText(String caddOnText) {
		this.caddOnText = caddOnText;
	}

	@Column(name = "NAREA_KEY", precision = 22, scale = 0)
	public BigDecimal getNareaKey() {
		return this.nareaKey;
	}

	public void setNareaKey(BigDecimal nareaKey) {
		this.nareaKey = nareaKey;
	}

	@Column(name = "CAREA_CODE", length = 40)
	public String getCareaCode() {
		return this.careaCode;
	}

	public void setCareaCode(String careaCode) {
		this.careaCode = careaCode;
	}

	@Column(name = "CAREA", length = 40)
	public String getCarea() {
		return this.carea;
	}

	public void setCarea(String carea) {
		this.carea = carea;
	}

	@Column(name = "CUNIT_OF_ISSUE", length = 12)
	public String getCunitOfIssue() {
		return this.cunitOfIssue;
	}

	public void setCunitOfIssue(String cunitOfIssue) {
		this.cunitOfIssue = cunitOfIssue;
	}

	@Column(name = "NWORKSTATION_KEY", precision = 22, scale = 0)
	public BigDecimal getNworkstationKey() {
		return this.nworkstationKey;
	}

	public void setNworkstationKey(BigDecimal nworkstationKey) {
		this.nworkstationKey = nworkstationKey;
	}

	@Column(name = "CWORKSTATION", length = 80)
	public String getCworkstation() {
		return this.cworkstation;
	}

	public void setCworkstation(String cworkstation) {
		this.cworkstation = cworkstation;
	}

	@Column(name = "CWORKSTATION_TEXT", length = 80)
	public String getCworkstationText() {
		return this.cworkstationText;
	}

	public void setCworkstationText(String cworkstationText) {
		this.cworkstationText = cworkstationText;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", precision = 22, scale = 0)
	public BigDecimal getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(BigDecimal npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NPACKINGLIST_DETAIL_KEY", precision = 22, scale = 0)
	public BigDecimal getNpackinglistDetailKey() {
		return this.npackinglistDetailKey;
	}

	public void setNpackinglistDetailKey(BigDecimal npackinglistDetailKey) {
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Column(name = "NQUANTITY", precision = 22, scale = 0)
	public BigDecimal getNquantity() {
		return this.nquantity;
	}

	public void setNquantity(BigDecimal nquantity) {
		this.nquantity = nquantity;
	}

	@Column(name = "NHEIGHT", precision = 22, scale = 0)
	public BigDecimal getNheight() {
		return this.nheight;
	}

	public void setNheight(BigDecimal nheight) {
		this.nheight = nheight;
	}

	@Column(name = "NWIDTH", precision = 22, scale = 0)
	public BigDecimal getNwidth() {
		return this.nwidth;
	}

	public void setNwidth(BigDecimal nwidth) {
		this.nwidth = nwidth;
	}

	@Column(name = "CCLASS", length = 4000)
	public String getCclass() {
		return this.cclass;
	}

	public void setCclass(String cclass) {
		this.cclass = cclass;
	}

	@Column(name = "NCLASS_NUMBER", precision = 22, scale = 0)
	public BigDecimal getNclassNumber() {
		return this.nclassNumber;
	}

	public void setNclassNumber(BigDecimal nclassNumber) {
		this.nclassNumber = nclassNumber;
	}

	@Column(name = "NPL_DISTRIBUTION_KEY", precision = 22, scale = 0)
	public BigDecimal getNplDistributionKey() {
		return this.nplDistributionKey;
	}

	public void setNplDistributionKey(BigDecimal nplDistributionKey) {
		this.nplDistributionKey = nplDistributionKey;
	}

	@Column(name = "NPRINT", precision = 22, scale = 0)
	public BigDecimal getNprint() {
		return this.nprint;
	}

	public void setNprint(BigDecimal nprint) {
		this.nprint = nprint;
	}

	@Column(name = "CMEAL_CONTROL_CODE", length = 12)
	public String getCmealControlCode() {
		return this.cmealControlCode;
	}

	public void setCmealControlCode(String cmealControlCode) {
		this.cmealControlCode = cmealControlCode;
	}

	@Column(name = "NLABEL_TYPE_KEY", precision = 22, scale = 0)
	public BigDecimal getNlabelTypeKey() {
		return this.nlabelTypeKey;
	}

	public void setNlabelTypeKey(BigDecimal nlabelTypeKey) {
		this.nlabelTypeKey = nlabelTypeKey;
	}

	@Column(name = "NLABEL_TYPE", precision = 22, scale = 0)
	public BigDecimal getNlabelType() {
		return this.nlabelType;
	}

	public void setNlabelType(BigDecimal nlabelType) {
		this.nlabelType = nlabelType;
	}

	@Column(name = "NDUPLICATED", precision = 22, scale = 0)
	public BigDecimal getNduplicated() {
		return this.nduplicated;
	}

	public void setNduplicated(BigDecimal nduplicated) {
		this.nduplicated = nduplicated;
	}

	@Column(name = "NUNIT_PRIORITY", precision = 22, scale = 0)
	public BigDecimal getNunitPriority() {
		return this.nunitPriority;
	}

	public void setNunitPriority(BigDecimal nunitPriority) {
		this.nunitPriority = nunitPriority;
	}

	@Column(name = "NCOMPUTE_LEG", precision = 22, scale = 0)
	public BigDecimal getNcomputeLeg() {
		return this.ncomputeLeg;
	}

	public void setNcomputeLeg(BigDecimal ncomputeLeg) {
		this.ncomputeLeg = ncomputeLeg;
	}

	@Column(name = "NSEPARATOR", precision = 22, scale = 0)
	public BigDecimal getNseparator() {
		return this.nseparator;
	}

	public void setNseparator(BigDecimal nseparator) {
		this.nseparator = nseparator;
	}

	@Column(name = "NMODIFIED", precision = 22, scale = 0)
	public BigDecimal getNmodified() {
		return this.nmodified;
	}

	public void setNmodified(BigDecimal nmodified) {
		this.nmodified = nmodified;
	}

	@Column(name = "NGALLEY_GROUP", precision = 22, scale = 0)
	public BigDecimal getNgalleyGroup() {
		return this.ngalleyGroup;
	}

	public void setNgalleyGroup(BigDecimal ngalleyGroup) {
		this.ngalleyGroup = ngalleyGroup;
	}

	@Column(name = "DPROD_DATE", length = 7)
	public Date getDprodDate() {
		return this.dprodDate;
	}

	public void setDprodDate(Date dprodDate) {
		this.dprodDate = dprodDate;
	}

	@Column(name = "NPLTYPE_KEY", precision = 22, scale = 0)
	public BigDecimal getNpltypeKey() {
		return this.npltypeKey;
	}

	public void setNpltypeKey(BigDecimal npltypeKey) {
		this.npltypeKey = npltypeKey;
	}

	@Column(name = "CPL_TYPE", length = 12)
	public String getCplType() {
		return this.cplType;
	}

	public void setCplType(String cplType) {
		this.cplType = cplType;
	}

	@Column(name = "NLABEL_COUNTER", precision = 22, scale = 0)
	public BigDecimal getNlabelCounter() {
		return this.nlabelCounter;
	}

	public void setNlabelCounter(BigDecimal nlabelCounter) {
		this.nlabelCounter = nlabelCounter;
	}

	@Column(name = "NCOMPUTE_NEXT_LEG", precision = 22, scale = 0)
	public BigDecimal getNcomputeNextLeg() {
		return this.ncomputeNextLeg;
	}

	public void setNcomputeNextLeg(BigDecimal ncomputeNextLeg) {
		this.ncomputeNextLeg = ncomputeNextLeg;
	}

	@Column(name = "NSECONDS", precision = 22, scale = 0)
	public BigDecimal getNseconds() {
		return this.nseconds;
	}

	public void setNseconds(BigDecimal nseconds) {
		this.nseconds = nseconds;
	}

	@Column(name = "NPHF_FLAG", precision = 22, scale = 0)
	public BigDecimal getNphfFlag() {
		return this.nphfFlag;
	}

	public void setNphfFlag(BigDecimal nphfFlag) {
		this.nphfFlag = nphfFlag;
	}

	@Column(name = "NRESERVE", precision = 22, scale = 0)
	public BigDecimal getNreserve() {
		return this.nreserve;
	}

	public void setNreserve(BigDecimal nreserve) {
		this.nreserve = nreserve;
	}

	@Column(name = "NQUANTITY_PROD", precision = 22, scale = 0)
	public BigDecimal getNquantityProd() {
		return this.nquantityProd;
	}

	public void setNquantityProd(BigDecimal nquantityProd) {
		this.nquantityProd = nquantityProd;
	}

	@Column(name = "NBATCH_NO", precision = 22, scale = 0)
	public BigDecimal getNbatchNo() {
		return this.nbatchNo;
	}

	public void setNbatchNo(BigDecimal nbatchNo) {
		this.nbatchNo = nbatchNo;
	}

	@Column(name = "DTIME_START", length = 7)
	public Date getDtimeStart() {
		return this.dtimeStart;
	}

	public void setDtimeStart(Date dtimeStart) {
		this.dtimeStart = dtimeStart;
	}

	@Column(name = "DTIME_STOP", length = 7)
	public Date getDtimeStop() {
		return this.dtimeStop;
	}

	public void setDtimeStop(Date dtimeStop) {
		this.dtimeStop = dtimeStop;
	}

	@Column(name = "NTEMP_START", precision = 22, scale = 0)
	public BigDecimal getNtempStart() {
		return this.ntempStart;
	}

	public void setNtempStart(BigDecimal ntempStart) {
		this.ntempStart = ntempStart;
	}

	@Column(name = "NTEMP_STOP", precision = 22, scale = 0)
	public BigDecimal getNtempStop() {
		return this.ntempStop;
	}

	public void setNtempStop(BigDecimal ntempStop) {
		this.ntempStop = ntempStop;
	}

	@Column(name = "NSTATUS", precision = 22, scale = 0)
	public BigDecimal getNstatus() {
		return this.nstatus;
	}

	public void setNstatus(BigDecimal nstatus) {
		this.nstatus = nstatus;
	}

	@Column(name = "NMANUAL_SPLIT", precision = 22, scale = 0)
	public BigDecimal getNmanualSplit() {
		return this.nmanualSplit;
	}

	public void setNmanualSplit(BigDecimal nmanualSplit) {
		this.nmanualSplit = nmanualSplit;
	}

	@Column(name = "CUSER_START", length = 40)
	public String getCuserStart() {
		return this.cuserStart;
	}

	public void setCuserStart(String cuserStart) {
		this.cuserStart = cuserStart;
	}

	@Column(name = "CUSER_STOP", length = 40)
	public String getCuserStop() {
		return this.cuserStop;
	}

	public void setCuserStop(String cuserStop) {
		this.cuserStop = cuserStop;
	}

	@Column(name = "NALERT_LEVEL", precision = 22, scale = 0)
	public BigDecimal getNalertLevel() {
		return this.nalertLevel;
	}

	public void setNalertLevel(BigDecimal nalertLevel) {
		this.nalertLevel = nalertLevel;
	}

	@Column(name = "CUNIT", length = 5)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "DCREATED_DATE", length = 7)
	public Date getDcreatedDate() {
		return this.dcreatedDate;
	}

	public void setDcreatedDate(Date dcreatedDate) {
		this.dcreatedDate = dcreatedDate;
	}

	@Column(name = "DUPDATED_DATE", length = 7)
	public Date getDupdatedDate() {
		return this.dupdatedDate;
	}

	public void setDupdatedDate(Date dupdatedDate) {
		this.dupdatedDate = dupdatedDate;
	}

	@Column(name = "CSEQUENCE", length = 40)
	public String getCsequence() {
		return this.csequence;
	}

	public void setCsequence(String csequence) {
		this.csequence = csequence;
	}

	@Column(name = "CUSER_DETAILS", length = 40)
	public String getCuserDetails() {
		return this.cuserDetails;
	}

	public void setCuserDetails(String cuserDetails) {
		this.cuserDetails = cuserDetails;
	}

	@Column(name = "CVERIFICATION_USER", length = 40)
	public String getCverificationUser() {
		return this.cverificationUser;
	}

	public void setCverificationUser(String cverificationUser) {
		this.cverificationUser = cverificationUser;
	}

	@Column(name = "DVERIFICATION_DATE", length = 7)
	public Date getDverificationDate() {
		return this.dverificationDate;
	}

	public void setDverificationDate(Date dverificationDate) {
		this.dverificationDate = dverificationDate;
	}

	@Column(name = "CREMARK_ACTION", length = 256)
	public String getCremarkAction() {
		return this.cremarkAction;
	}

	public void setCremarkAction(String cremarkAction) {
		this.cremarkAction = cremarkAction;
	}

	@Column(name = "CWO_DESCRIPTION", length = 40)
	public String getCwoDescription() {
		return this.cwoDescription;
	}

	public void setCwoDescription(String cwoDescription) {
		this.cwoDescription = cwoDescription;
	}

	@Column(name = "NWO_OFFSET", precision = 22, scale = 0)
	public BigDecimal getNwoOffset() {
		return this.nwoOffset;
	}

	public void setNwoOffset(BigDecimal nwoOffset) {
		this.nwoOffset = nwoOffset;
	}

	@Column(name = "CWO_TIME_FROM", length = 5)
	public String getCwoTimeFrom() {
		return this.cwoTimeFrom;
	}

	public void setCwoTimeFrom(String cwoTimeFrom) {
		this.cwoTimeFrom = cwoTimeFrom;
	}

	@Column(name = "CWO_TIME_TO", length = 5)
	public String getCwoTimeTo() {
		return this.cwoTimeTo;
	}

	public void setCwoTimeTo(String cwoTimeTo) {
		this.cwoTimeTo = cwoTimeTo;
	}

	@Column(name = "NMAX_BATCH_SIZE", precision = 22, scale = 0)
	public BigDecimal getNmaxBatchSize() {
		return this.nmaxBatchSize;
	}

	public void setNmaxBatchSize(BigDecimal nmaxBatchSize) {
		this.nmaxBatchSize = nmaxBatchSize;
	}

	@Column(name = "NSEQUENCE", precision = 22, scale = 0)
	public BigDecimal getNsequence() {
		return this.nsequence;
	}

	public void setNsequence(BigDecimal nsequence) {
		this.nsequence = nsequence;
	}

	@Column(name = "NEMP_COUNT", precision = 22, scale = 0)
	public BigDecimal getNempCount() {
		return this.nempCount;
	}

	public void setNempCount(BigDecimal nempCount) {
		this.nempCount = nempCount;
	}

	@Column(name = "DPLANNED_START", length = 7)
	public Date getDplannedStart() {
		return this.dplannedStart;
	}

	public void setDplannedStart(Date dplannedStart) {
		this.dplannedStart = dplannedStart;
	}

	@Column(name = "DPLANNED_END", length = 7)
	public Date getDplannedEnd() {
		return this.dplannedEnd;
	}

	public void setDplannedEnd(Date dplannedEnd) {
		this.dplannedEnd = dplannedEnd;
	}

	@Column(name = "NDURATION", precision = 22, scale = 0)
	public BigDecimal getNduration() {
		return this.nduration;
	}

	public void setNduration(BigDecimal nduration) {
		this.nduration = nduration;
	}

	@Column(name = "NWORKSCHEDULE_INDEX", precision = 22, scale = 0)
	public Long getNworkscheduleIndex() {
		return this.nworkscheduleIndex;
	}

	public void setNworkscheduleIndex(Long nworkscheduleIndex) {
		this.nworkscheduleIndex = nworkscheduleIndex;
	}

	@Column(name = "CTEXT_SHORT", length = 170)
	public String getCtextShort() {
		return this.ctextShort;
	}

	public void setCtextShort(String ctextShort) {
		this.ctextShort = ctextShort;
	}

	@Column(name = "CUSER_START2", length = 40)
	public String getCuserStart2() {
		return this.cuserStart2;
	}

	public void setCuserStart2(String cuserStart2) {
		this.cuserStart2 = cuserStart2;
	}

	@Column(name = "CUSER_START3", length = 40)
	public String getCuserStart3() {
		return this.cuserStart3;
	}

	public void setCuserStart3(String cuserStart3) {
		this.cuserStart3 = cuserStart3;
	}

	@Column(name = "CSCHEDULE", length = 40)
	public String getCschedule() {
		return this.cschedule;
	}

	public void setCschedule(String cschedule) {
		this.cschedule = cschedule;
	}

	@Column(name = "NPPM_SCHED_KEY", precision = 12, scale = 0)
	public Long getNppmSchedKey() {
		return this.nppmSchedKey;
	}

	public void setNppmSchedKey(Long nppmSchedKey) {
		this.nppmSchedKey = nppmSchedKey;
	}

	@Column(name = "NROOM_TEMP", precision = 22, scale = 0)
	public BigDecimal getNroomTemp() {
		return this.nroomTemp;
	}

	public void setNroomTemp(BigDecimal nroomTemp) {
		this.nroomTemp = nroomTemp;
	}

	@Column(name = "NGOLD_STANDARD", precision = 22, scale = 0)
	public BigDecimal getNgoldStandard() {
		return this.ngoldStandard;
	}

	public void setNgoldStandard(BigDecimal ngoldStandard) {
		this.ngoldStandard = ngoldStandard;
	}

	@Column(name = "NMOVED", precision = 22, scale = 0)
	public BigDecimal getNmoved() {
		return this.nmoved;
	}

	public void setNmoved(BigDecimal nmoved) {
		this.nmoved = nmoved;
	}

	@Column(name = "NQUANTITY_PROD_PLANNED", precision = 22, scale = 0)
	public BigDecimal getNquantityProdPlanned() {
		return this.nquantityProdPlanned;
	}

	public void setNquantityProdPlanned(BigDecimal nquantityProdPlanned) {
		this.nquantityProdPlanned = nquantityProdPlanned;
	}

	@Column(name = "NDURATION_SYNC", precision = 22, scale = 0)
	public BigDecimal getNdurationSync() {
		return this.ndurationSync;
	}

	public void setNdurationSync(BigDecimal ndurationSync) {
		this.ndurationSync = ndurationSync;
	}

	@Column(name = "NINSERT_BY_SYNC", precision = 22, scale = 0)
	public BigDecimal getNinsertBySync() {
		return this.ninsertBySync;
	}

	public void setNinsertBySync(BigDecimal ninsertBySync) {
		this.ninsertBySync = ninsertBySync;
	}

	@Column(name = "NCAPACITY", precision = 22, scale = 0)
	public BigDecimal getNcapacity() {
		return this.ncapacity;
	}

	public void setNcapacity(BigDecimal ncapacity) {
		this.ncapacity = ncapacity;
	}

	@Column(name = "CUNIT_CAPACITY", length = 40)
	public String getCunitCapacity() {
		return this.cunitCapacity;
	}

	public void setCunitCapacity(String cunitCapacity) {
		this.cunitCapacity = cunitCapacity;
	}

	@Column(name = "NRUNRATE", precision = 22, scale = 0)
	public BigDecimal getNrunrate() {
		return this.nrunrate;
	}

	public void setNrunrate(BigDecimal nrunrate) {
		this.nrunrate = nrunrate;
	}

	@Column(name = "NSETUPRATE", precision = 22, scale = 0)
	public BigDecimal getNsetuprate() {
		return this.nsetuprate;
	}

	public void setNsetuprate(BigDecimal nsetuprate) {
		this.nsetuprate = nsetuprate;
	}

	@Column(name = "CUSER_LOCK", length = 40)
	public String getCuserLock() {
		return this.cuserLock;
	}

	public void setCuserLock(String cuserLock) {
		this.cuserLock = cuserLock;
	}

	@Column(name = "NPPMTRAIL_KEY", precision = 22, scale = 0)
	public BigDecimal getNppmtrailKey() {
		return this.nppmtrailKey;
	}

	public void setNppmtrailKey(BigDecimal nppmtrailKey) {
		this.nppmtrailKey = nppmtrailKey;
	}

	@Column(name = "CTEXT_LOC_UNIT_PL_PROD_LABEL", length = 40)
	public String getCtextLocUnitPlProdLabel() {
		return this.ctextLocUnitPlProdLabel;
	}

	public void setCtextLocUnitPlProdLabel(String ctextLocUnitPlProdLabel) {
		this.ctextLocUnitPlProdLabel = ctextLocUnitPlProdLabel;
	}

	@Column(name = "NSECTOR_KEY", precision = 22, scale = 0)
	public BigDecimal getNsectorKey() {
		return this.nsectorKey;
	}

	public void setNsectorKey(BigDecimal nsectorKey) {
		this.nsectorKey = nsectorKey;
	}

	@Column(name = "CSECTOR", length = 40)
	public String getCsector() {
		return this.csector;
	}

	public void setCsector(String csector) {
		this.csector = csector;
	}

	@Column(name = "NBATCH_SEQ_PROD_LABEL", precision = 22, scale = 0)
	public BigDecimal getNbatchSeqProdLabel() {
		return this.nbatchSeqProdLabel;
	}

	public void setNbatchSeqProdLabel(BigDecimal nbatchSeqProdLabel) {
		this.nbatchSeqProdLabel = nbatchSeqProdLabel;
	}

	@Column(name = "NAMBIENT_TRAY", precision = 22, scale = 0)
	public BigDecimal getNambientTray() {
		return this.nambientTray;
	}

	public void setNambientTray(BigDecimal nambientTray) {
		this.nambientTray = nambientTray;
	}

	@Column(name = "NPL_KIND_KEY", precision = 22, scale = 0)
	public BigDecimal getNplKindKey() {
		return this.nplKindKey;
	}

	public void setNplKindKey(BigDecimal nplKindKey) {
		this.nplKindKey = nplKindKey;
	}

	@Column(name = "NGALLEY_KEY", precision = 22, scale = 0)
	public BigDecimal getNgalleyKey() {
		return this.ngalleyKey;
	}

	public void setNgalleyKey(BigDecimal ngalleyKey) {
		this.ngalleyKey = ngalleyKey;
	}

	@Column(name = "CGALLEY", length = 12)
	public String getCgalley() {
		return this.cgalley;
	}

	public void setCgalley(String cgalley) {
		this.cgalley = cgalley;
	}

	@Column(name = "NSTOWAGE_KEY", precision = 22, scale = 0)
	public BigDecimal getNstowageKey() {
		return this.nstowageKey;
	}

	public void setNstowageKey(BigDecimal nstowageKey) {
		this.nstowageKey = nstowageKey;
	}

	@Column(name = "CSTOWAGE", length = 12)
	public String getCstowage() {
		return this.cstowage;
	}

	public void setCstowage(String cstowage) {
		this.cstowage = cstowage;
	}

	@Column(name = "CPLACE", length = 12)
	public String getCplace() {
		return this.cplace;
	}

	public void setCplace(String cplace) {
		this.cplace = cplace;
	}

	@Column(name = "NGALLEY_SORT", precision = 22, scale = 0)
	public BigDecimal getNgalleySort() {
		return this.ngalleySort;
	}

	public void setNgalleySort(BigDecimal ngalleySort) {
		this.ngalleySort = ngalleySort;
	}

	@Column(name = "NSTOWAGE_SORT", precision = 22, scale = 0)
	public BigDecimal getNstowageSort() {
		return this.nstowageSort;
	}

	public void setNstowageSort(BigDecimal nstowageSort) {
		this.nstowageSort = nstowageSort;
	}

	@Column(name = "NBELLY_CONTAINER", precision = 22, scale = 0)
	public BigDecimal getNbellyContainer() {
		return this.nbellyContainer;
	}

	public void setNbellyContainer(BigDecimal nbellyContainer) {
		this.nbellyContainer = nbellyContainer;
	}

	@Column(name = "NCHANGE_OVER_TIME", precision = 22, scale = 0)
	public BigDecimal getNchangeOverTime() {
		return this.nchangeOverTime;
	}

	public void setNchangeOverTime(BigDecimal nchangeOverTime) {
		this.nchangeOverTime = nchangeOverTime;
	}

	@Column(name = "CSERVING_UNIT", length = 4)
	public String getCservingUnit() {
		return this.cservingUnit;
	}

	public void setCservingUnit(String cservingUnit) {
		this.cservingUnit = cservingUnit;
	}

	@Column(name = "NINCREASE_LABELS_PRINTED", precision = 22, scale = 0)
	public BigDecimal getNincreaseLabelsPrinted() {
		return this.nincreaseLabelsPrinted;
	}

	public void setNincreaseLabelsPrinted(BigDecimal nincreaseLabelsPrinted) {
		this.nincreaseLabelsPrinted = nincreaseLabelsPrinted;
	}

	@Column(name = "NPREPRODUCTION", precision = 22, scale = 0)
	public BigDecimal getNpreproduction() {
		return this.npreproduction;
	}

	public void setNpreproduction(BigDecimal npreproduction) {
		this.npreproduction = npreproduction;
	}

	@Column(name = "NQUANTITY_INVENTORY", precision = 22, scale = 0)
	public BigDecimal getNquantityInventory() {
		return this.nquantityInventory;
	}

	public void setNquantityInventory(BigDecimal nquantityInventory) {
		this.nquantityInventory = nquantityInventory;
	}

	@Column(name = "NTEMP_COOKING_FINISHED", precision = 22, scale = 0)
	public BigDecimal getNtempCookingFinished() {
		return this.ntempCookingFinished;
	}

	public void setNtempCookingFinished(BigDecimal ntempCookingFinished) {
		this.ntempCookingFinished = ntempCookingFinished;
	}

	@Column(name = "DTIME_COOKING_FINISHED", length = 7)
	public Date getDtimeCookingFinished() {
		return this.dtimeCookingFinished;
	}

	public void setDtimeCookingFinished(Date dtimeCookingFinished) {
		this.dtimeCookingFinished = dtimeCookingFinished;
	}

	@Column(name = "CUSER_COOKING_FINISHED", length = 40)
	public String getCuserCookingFinished() {
		return this.cuserCookingFinished;
	}

	public void setCuserCookingFinished(String cuserCookingFinished) {
		this.cuserCookingFinished = cuserCookingFinished;
	}

	@Column(name = "NPRODUCT_SEARED", precision = 22, scale = 0)
	public BigDecimal getNproductSeared() {
		return this.nproductSeared;
	}

	public void setNproductSeared(BigDecimal nproductSeared) {
		this.nproductSeared = nproductSeared;
	}

	@Column(name = "NTEMP_CHILLING_STARTED", precision = 22, scale = 0)
	public BigDecimal getNtempChillingStarted() {
		return this.ntempChillingStarted;
	}

	public void setNtempChillingStarted(BigDecimal ntempChillingStarted) {
		this.ntempChillingStarted = ntempChillingStarted;
	}

	@Column(name = "DTIME_CHILLING_STARTED", length = 7)
	public Date getDtimeChillingStarted() {
		return this.dtimeChillingStarted;
	}

	public void setDtimeChillingStarted(Date dtimeChillingStarted) {
		this.dtimeChillingStarted = dtimeChillingStarted;
	}

	@Column(name = "NTEMP_CHILLING_FINISHED", precision = 22, scale = 0)
	public BigDecimal getNtempChillingFinished() {
		return this.ntempChillingFinished;
	}

	public void setNtempChillingFinished(BigDecimal ntempChillingFinished) {
		this.ntempChillingFinished = ntempChillingFinished;
	}

	@Column(name = "DTIME_CHILLING_FINISHED", length = 7)
	public Date getDtimeChillingFinished() {
		return this.dtimeChillingFinished;
	}

	public void setDtimeChillingFinished(Date dtimeChillingFinished) {
		this.dtimeChillingFinished = dtimeChillingFinished;
	}

	@Column(name = "CUSER_CHILLING_FINISHED", length = 40)
	public String getCuserChillingFinished() {
		return this.cuserChillingFinished;
	}

	public void setCuserChillingFinished(String cuserChillingFinished) {
		this.cuserChillingFinished = cuserChillingFinished;
	}

	@Column(name = "NSHORTAGEWASTAGE_KEY", precision = 22, scale = 0)
	public BigDecimal getNshortagewastageKey() {
		return this.nshortagewastageKey;
	}

	public void setNshortagewastageKey(BigDecimal nshortagewastageKey) {
		this.nshortagewastageKey = nshortagewastageKey;
	}

	@Column(name = "NQUANTITY_VERS", precision = 22, scale = 0)
	public BigDecimal getNquantityVers() {
		return this.nquantityVers;
	}

	public void setNquantityVers(BigDecimal nquantityVers) {
		this.nquantityVers = nquantityVers;
	}
}


