package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 22.08.2017 08:17:04 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPpmFlightSectorId generated by hbm2java
 */
@Embeddable
public class CenOutPpmFlightSectorId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nresultKey;
	private long nsectorKey;

	public CenOutPpmFlightSectorId() {
	}

	public CenOutPpmFlightSectorId(final long nresultKey, final long nsectorKey) {
		this.nresultKey = nresultKey;
		this.nsectorKey = nsectorKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NSECTOR_KEY", nullable = false, precision = 12, scale = 0)
	public long getNsectorKey() {
		return this.nsectorKey;
	}

	public void setNsectorKey(final long nsectorKey) {
		this.nsectorKey = nsectorKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutPpmFlightSectorId)) {
			return false;
		}
		final CenOutPpmFlightSectorId castOther = (CenOutPpmFlightSectorId) other;

		return (this.getNresultKey() == castOther.getNresultKey())
				&& (this.getNsectorKey() == castOther.getNsectorKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNsectorKey();
		return result;
	}

}
