package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutDocumentsId generated by hbm2java
 */
@Embeddable
public class CenOutDocumentsId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nresultKey;
	private long ntransaction;
	private String cuser;

	public CenOutDocumentsId() {
	}

	public CenOutDocumentsId(final long nresultKey, final long ntransaction, final String cuser) {
		this.nresultKey = nresultKey;
		this.ntransaction = ntransaction;
		this.cuser = cuser;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NTRANSACTION", nullable = false, precision = 12, scale = 0)
	public long getNtransaction() {
		return this.ntransaction;
	}

	public void setNtransaction(final long ntransaction) {
		this.ntransaction = ntransaction;
	}

	@Column(name = "CUSER", nullable = false, length = 15)
	public String getCuser() {
		return this.cuser;
	}

	public void setCuser(final String cuser) {
		this.cuser = cuser;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenOutDocumentsId)) {
			return false;
		}
		final CenOutDocumentsId castOther = (CenOutDocumentsId) other;

		return this.getNresultKey() == castOther.getNresultKey()
				&& this.getNtransaction() == castOther.getNtransaction()
				&& (this.getCuser() == castOther.getCuser()
						|| this.getCuser() != null && castOther.getCuser() != null && this.getCuser().equals(castOther.getCuser()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNtransaction();
		result = 37 * result + (getCuser() == null ? 0 : this.getCuser().hashCode());
		return result;
	}

}
