package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 12.10.2022 09:36:43 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutSpmlDetailHistoryId generated by hbm2java
 */
@Embeddable
public class CenOutSpmlDetailHistoryId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long ndetailKey;
     private long ntransaction;

    public CenOutSpmlDetailHistoryId() {
    }

    public CenOutSpmlDetailHistoryId(long ndetailKey, long ntransaction) {
       this.ndetailKey = ndetailKey;
       this.ntransaction = ntransaction;
    }
   


    @Column(name="NDETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNdetailKey() {
        return this.ndetailKey;
    }
    
    public void setNdetailKey(long ndetailKey) {
        this.ndetailKey = ndetailKey;
    }


    @Column(name="NTRANSACTION", nullable=false, precision=12, scale=0)
    public long getNtransaction() {
        return this.ntransaction;
    }
    
    public void setNtransaction(long ntransaction) {
        this.ntransaction = ntransaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenOutSpmlDetailHistoryId) ) return false;
		 CenOutSpmlDetailHistoryId castOther = ( CenOutSpmlDetailHistoryId ) other; 
         
		 return (this.getNdetailKey()==castOther.getNdetailKey())
 && (this.getNtransaction()==castOther.getNtransaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNdetailKey();
         result = 37 * result + (int) this.getNtransaction();
         return result;
   }   


}


