package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated May 18, 2017 11:11:23 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPpmPrLabDtlTpId generated by hbm2java
 */
@Embeddable
public class CenOutPpmPrLabDtlTpId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nppmPrLabDetailKey;
	private long nppmtrailDetailKey;

	public CenOutPpmPrLabDtlTpId() {
	}

	public CenOutPpmPrLabDtlTpId(final long nppmPrLabDetailKey, final long nppmtrailDetailKey) {
		this.nppmPrLabDetailKey = nppmPrLabDetailKey;
		this.nppmtrailDetailKey = nppmtrailDetailKey;
	}

	@Column(name = "NPPM_PR_LAB_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNppmPrLabDetailKey() {
		return this.nppmPrLabDetailKey;
	}

	public void setNppmPrLabDetailKey(final long nppmPrLabDetailKey) {
		this.nppmPrLabDetailKey = nppmPrLabDetailKey;
	}

	@Column(name = "NPPMTRAIL_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNppmtrailDetailKey() {
		return this.nppmtrailDetailKey;
	}

	public void setNppmtrailDetailKey(final long nppmtrailDetailKey) {
		this.nppmtrailDetailKey = nppmtrailDetailKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutPpmPrLabDtlTpId)) {
			return false;
		}
		final CenOutPpmPrLabDtlTpId castOther = (CenOutPpmPrLabDtlTpId) other;

		return (this.getNppmPrLabDetailKey() == castOther.getNppmPrLabDetailKey())
				&& (this.getNppmtrailDetailKey() == castOther.getNppmtrailDetailKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNppmPrLabDetailKey();
		result = 37 * result + (int) this.getNppmtrailDetailKey();
		return result;
	}

}
