package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutSdId generated by hbm2java
 */
@Embeddable
public class CenOutSdId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nresultKey;
	private long ntransaction;
	private long nrowid;

	public CenOutSdId() {
	}

	public CenOutSdId(final long nresultKey, final long ntransaction, final long nrowid) {
		this.nresultKey = nresultKey;
		this.ntransaction = ntransaction;
		this.nrowid = nrowid;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NTRANSACTION", nullable = false, precision = 12, scale = 0)
	public long getNtransaction() {
		return this.ntransaction;
	}

	public void setNtransaction(final long ntransaction) {
		this.ntransaction = ntransaction;
	}

	@Column(name = "NROWID", nullable = false, precision = 12, scale = 0)
	public long getNrowid() {
		return this.nrowid;
	}

	public void setNrowid(final long nrowid) {
		this.nrowid = nrowid;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenOutSdId)) {
			return false;
		}
		final CenOutSdId castOther = (CenOutSdId) other;

		return this.getNresultKey() == castOther.getNresultKey()
				&& this.getNtransaction() == castOther.getNtransaction()
				&& this.getNrowid() == castOther.getNrowid();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNtransaction();
		result = 37 * result + (int) this.getNrowid();
		return result;
	}

}
