package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 09.03.2020 14:54:27 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPaxHistoryId generated by hbm2java
 */
@Embeddable
public class CenOutPaxHistoryId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nresultKey;
     private long nclassNumber;
     private long ntransaction;

    public CenOutPaxHistoryId() {
    }

    public CenOutPaxHistoryId(long nresultKey, long nclassNumber, long ntransaction) {
       this.nresultKey = nresultKey;
       this.nclassNumber = nclassNumber;
       this.ntransaction = ntransaction;
    }
   


    @Column(name="NRESULT_KEY", nullable=false, precision=12, scale=0)
    public long getNresultKey() {
        return this.nresultKey;
    }
    
    public void setNresultKey(long nresultKey) {
        this.nresultKey = nresultKey;
    }


    @Column(name="NCLASS_NUMBER", nullable=false, precision=12, scale=0)
    public long getNclassNumber() {
        return this.nclassNumber;
    }
    
    public void setNclassNumber(long nclassNumber) {
        this.nclassNumber = nclassNumber;
    }


    @Column(name="NTRANSACTION", nullable=false, precision=12, scale=0)
    public long getNtransaction() {
        return this.ntransaction;
    }
    
    public void setNtransaction(long ntransaction) {
        this.ntransaction = ntransaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenOutPaxHistoryId) ) return false;
		 CenOutPaxHistoryId castOther = ( CenOutPaxHistoryId ) other; 
         
		 return (this.getNresultKey()==castOther.getNresultKey())
 && (this.getNclassNumber()==castOther.getNclassNumber())
 && (this.getNtransaction()==castOther.getNtransaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNresultKey();
         result = 37 * result + (int) this.getNclassNumber();
         result = 37 * result + (int) this.getNtransaction();
         return result;
   }   


}


