package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 12.10.2022 09:36:43 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutSpmlHistoryId generated by hbm2java
 */
@Embeddable
public class CenOutSpmlHistoryId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nmasterKey;
     private long ntransaction;

    public CenOutSpmlHistoryId() {
    }

    public CenOutSpmlHistoryId(long nmasterKey, long ntransaction) {
       this.nmasterKey = nmasterKey;
       this.ntransaction = ntransaction;
    }
   


    @Column(name="NMASTER_KEY", nullable=false, precision=12, scale=0)
    public long getNmasterKey() {
        return this.nmasterKey;
    }
    
    public void setNmasterKey(long nmasterKey) {
        this.nmasterKey = nmasterKey;
    }


    @Column(name="NTRANSACTION", nullable=false, precision=12, scale=0)
    public long getNtransaction() {
        return this.ntransaction;
    }
    
    public void setNtransaction(long ntransaction) {
        this.ntransaction = ntransaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenOutSpmlHistoryId) ) return false;
		 CenOutSpmlHistoryId castOther = ( CenOutSpmlHistoryId ) other; 
         
		 return (this.getNmasterKey()==castOther.getNmasterKey())
 && (this.getNtransaction()==castOther.getNtransaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNmasterKey();
         result = 37 * result + (int) this.getNtransaction();
         return result;
   }   


}


