package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jan 24, 2018 3:32:21 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPpmLabelCoId generated by hbm2java
 */
@Embeddable
public class CenOutPpmLabelCoId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nppmProdLabelKey;
	private long npackinglistIndexKey;
	private long nclassNumber;

	public CenOutPpmLabelCoId() {
	}

	public CenOutPpmLabelCoId(final long nppmProdLabelKey, final long npackinglistIndexKey, final long nclassNumber) {
		this.nppmProdLabelKey = nppmProdLabelKey;
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.nclassNumber = nclassNumber;
	}

	@Column(name = "NPPM_PROD_LABEL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNppmProdLabelKey() {
		return this.nppmProdLabelKey;
	}

	public void setNppmProdLabelKey(final long nppmProdLabelKey) {
		this.nppmProdLabelKey = nppmProdLabelKey;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(final long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NCLASS_NUMBER", nullable = false, precision = 12, scale = 0)
	public long getNclassNumber() {
		return this.nclassNumber;
	}

	public void setNclassNumber(final long nclassNumber) {
		this.nclassNumber = nclassNumber;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutPpmLabelCoId)) {
			return false;
		}
		final CenOutPpmLabelCoId castOther = (CenOutPpmLabelCoId) other;

		return (this.getNppmProdLabelKey() == castOther.getNppmProdLabelKey())
				&& (this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey())
				&& (this.getNclassNumber() == castOther.getNclassNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNppmProdLabelKey();
		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNclassNumber();
		return result;
	}

}
