package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 11.01.2018 14:26:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPpmProdLabelPdfId generated by hbm2java
 */
@Embeddable
public class CenOutPpmProdLabelPdfId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nbatchSeq;
	private long nlabelTypeKey;

	public CenOutPpmProdLabelPdfId() {
	}

	public CenOutPpmProdLabelPdfId(final long nbatchSeq, final long nlabelTypeKey) {
		this.nbatchSeq = nbatchSeq;
		this.nlabelTypeKey = nlabelTypeKey;
	}

	@Column(name = "NBATCH_SEQ", nullable = false, precision = 12, scale = 0)
	public long getNbatchSeq() {
		return this.nbatchSeq;
	}

	public void setNbatchSeq(final long nbatchSeq) {
		this.nbatchSeq = nbatchSeq;
	}

	@Column(name = "NLABEL_TYPE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlabelTypeKey() {
		return this.nlabelTypeKey;
	}

	public void setNlabelTypeKey(final long nlabelTypeKey) {
		this.nlabelTypeKey = nlabelTypeKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutPpmProdLabelPdfId)) {
			return false;
		}
		final CenOutPpmProdLabelPdfId castOther = (CenOutPpmProdLabelPdfId) other;

		return (this.getNbatchSeq() == castOther.getNbatchSeq())
				&& (this.getNlabelTypeKey() == castOther.getNlabelTypeKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNbatchSeq();
		result = 37 * result + (int) this.getNlabelTypeKey();
		return result;
	}

}
