package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Sep 15, 2017 7:52:18 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutCartdiagramsId generated by hbm2java
 */
@Embeddable
public class CenOutCartdiagramsId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nresultKey;
	private long ntransaction;
	private String ctype;
	private int ncounter;

	public CenOutCartdiagramsId() {
	}

	public CenOutCartdiagramsId(final long nresultKey, final long ntransaction, final String ctype, final int ncounter) {
		this.nresultKey = nresultKey;
		this.ntransaction = ntransaction;
		this.ctype = ctype;
		this.ncounter = ncounter;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NTRANSACTION", nullable = false, precision = 12, scale = 0)
	public long getNtransaction() {
		return this.ntransaction;
	}

	public void setNtransaction(final long ntransaction) {
		this.ntransaction = ntransaction;
	}

	@Column(name = "CTYPE", nullable = false, length = 10)
	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(final String ctype) {
		this.ctype = ctype;
	}

	@Column(name = "NCOUNTER", nullable = false, precision = 4, scale = 0)
	public int getNcounter() {
		return this.ncounter;
	}

	public void setNcounter(final int ncounter) {
		this.ncounter = ncounter;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenOutCartdiagramsId)) {
			return false;
		}
		final CenOutCartdiagramsId castOther = (CenOutCartdiagramsId) other;

		return (this.getNresultKey() == castOther.getNresultKey())
				&& (this.getNtransaction() == castOther.getNtransaction())
				&& ((this.getCtype() == castOther.getCtype())
						|| (this.getCtype() != null && castOther.getCtype() != null && this.getCtype().equals(castOther.getCtype())))
				&& (this.getNcounter() == castOther.getNcounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNtransaction();
		result = 37 * result + (getCtype() == null ? 0 : this.getCtype().hashCode());
		result = 37 * result + this.getNcounter();
		return result;
	}

}
