package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 12.10.2022 09:36:43 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutHandlingHistoryId generated by hbm2java
 */
@Embeddable
public class CenOutHandlingHistoryId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nresultKey;
     private long nhandlingId;
     private long nloadinglistIndexKey;
     private long ntransaction;

    public CenOutHandlingHistoryId() {
    }

    public CenOutHandlingHistoryId(long nresultKey, long nhandlingId, long nloadinglistIndexKey, long ntransaction) {
       this.nresultKey = nresultKey;
       this.nhandlingId = nhandlingId;
       this.nloadinglistIndexKey = nloadinglistIndexKey;
       this.ntransaction = ntransaction;
    }
   


    @Column(name="NRESULT_KEY", nullable=false, precision=12, scale=0)
    public long getNresultKey() {
        return this.nresultKey;
    }
    
    public void setNresultKey(long nresultKey) {
        this.nresultKey = nresultKey;
    }


    @Column(name="NHANDLING_ID", nullable=false, precision=12, scale=0)
    public long getNhandlingId() {
        return this.nhandlingId;
    }
    
    public void setNhandlingId(long nhandlingId) {
        this.nhandlingId = nhandlingId;
    }


    @Column(name="NLOADINGLIST_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNloadinglistIndexKey() {
        return this.nloadinglistIndexKey;
    }
    
    public void setNloadinglistIndexKey(long nloadinglistIndexKey) {
        this.nloadinglistIndexKey = nloadinglistIndexKey;
    }


    @Column(name="NTRANSACTION", nullable=false, precision=12, scale=0)
    public long getNtransaction() {
        return this.ntransaction;
    }
    
    public void setNtransaction(long ntransaction) {
        this.ntransaction = ntransaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenOutHandlingHistoryId) ) return false;
		 CenOutHandlingHistoryId castOther = ( CenOutHandlingHistoryId ) other; 
         
		 return (this.getNresultKey()==castOther.getNresultKey())
 && (this.getNhandlingId()==castOther.getNhandlingId())
 && (this.getNloadinglistIndexKey()==castOther.getNloadinglistIndexKey())
 && (this.getNtransaction()==castOther.getNtransaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNresultKey();
         result = 37 * result + (int) this.getNhandlingId();
         result = 37 * result + (int) this.getNloadinglistIndexKey();
         result = 37 * result + (int) this.getNtransaction();
         return result;
   }   


}


