package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutPaxId generated by hbm2java
 */
@Embeddable
public class CenOutPaxId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nresultKey;
	private long nclassNumber;

	public CenOutPaxId() {
	}

	public CenOutPaxId(final long nresultKey, final long nclassNumber) {
		this.nresultKey = nresultKey;
		this.nclassNumber = nclassNumber;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NCLASS_NUMBER", nullable = false, precision = 12, scale = 0)
	public long getNclassNumber() {
		return this.nclassNumber;
	}

	public void setNclassNumber(final long nclassNumber) {
		this.nclassNumber = nclassNumber;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenOutPaxId)) {
			return false;
		}
		final CenOutPaxId castOther = (CenOutPaxId) other;

		return this.getNresultKey() == castOther.getNresultKey()
				&& this.getNclassNumber() == castOther.getNclassNumber();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNclassNumber();
		return result;
	}

}
