package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenOutHandlingId generated by hbm2java
 */
@Embeddable
public class CenOutHandlingId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nresultKey;
	private long nhandlingId;
	private long nloadinglistIndexKey;

	public CenOutHandlingId() {
	}

	public CenOutHandlingId(final long nresultKey, final long nhandlingId, final long nloadinglistIndexKey) {
		this.nresultKey = nresultKey;
		this.nhandlingId = nhandlingId;
		this.nloadinglistIndexKey = nloadinglistIndexKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NHANDLING_ID", nullable = false, precision = 12, scale = 0)
	public long getNhandlingId() {
		return this.nhandlingId;
	}

	public void setNhandlingId(final long nhandlingId) {
		this.nhandlingId = nhandlingId;
	}

	@Column(name = "NLOADINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNloadinglistIndexKey() {
		return this.nloadinglistIndexKey;
	}

	public void setNloadinglistIndexKey(final long nloadinglistIndexKey) {
		this.nloadinglistIndexKey = nloadinglistIndexKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenOutHandlingId)) {
			return false;
		}
		final CenOutHandlingId castOther = (CenOutHandlingId) other;

		return this.getNresultKey() == castOther.getNresultKey()
				&& this.getNhandlingId() == castOther.getNhandlingId()
				&& this.getNloadinglistIndexKey() == castOther.getNloadinglistIndexKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNhandlingId();
		result = 37 * result + (int) this.getNloadinglistIndexKey();
		return result;
	}

}
