package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Mar 17, 2025 12:31:04 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPackinglistFlagsId generated by hbm2java
 */
@Embeddable
public class CenPackinglistFlagsId  implements java.io.Serializable {


     private long npackinglistIndexKey;
     private long npackinglistDetailKey;
     private long nflagId;


    @Column(name="NPACKINGLIST_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistIndexKey() {
        return this.npackinglistIndexKey;
    }
    
    public void setNpackinglistIndexKey(long npackinglistIndexKey) {
        this.npackinglistIndexKey = npackinglistIndexKey;
    }


    @Column(name="NPACKINGLIST_DETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistDetailKey() {
        return this.npackinglistDetailKey;
    }
    
    public void setNpackinglistDetailKey(long npackinglistDetailKey) {
        this.npackinglistDetailKey = npackinglistDetailKey;
    }


    @Column(name="NFLAG_ID", nullable=false, precision=12, scale=0)
    public long getNflagId() {
        return this.nflagId;
    }
    
    public void setNflagId(long nflagId) {
        this.nflagId = nflagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenPackinglistFlagsId) ) return false;
		 CenPackinglistFlagsId castOther = ( CenPackinglistFlagsId ) other; 
         
		 return (this.getNpackinglistIndexKey()==castOther.getNpackinglistIndexKey())
 && (this.getNpackinglistDetailKey()==castOther.getNpackinglistDetailKey())
 && (this.getNflagId()==castOther.getNflagId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNpackinglistIndexKey();
         result = 37 * result + (int) this.getNpackinglistDetailKey();
         result = 37 * result + (int) this.getNflagId();
         return result;
   }   


}


