package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * CenPackinglistsId generated by hbm2java<br>
 * This PrimaryKey is used for different objects {@link CenPackinglists}, {@link CenPackinglistInstructions}, {@link CenPackinglistPictures}
 * {@link CenPackinglistIf}
 */
@Embeddable
public class CenPackinglistsId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long npackinglistIndexKey;

	private long npackinglistDetailKey;

	public CenPackinglistsId() {
	}

	public CenPackinglistsId(final long npackinglistIndexKey, final long npackinglistDetailKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(final long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NPACKINGLIST_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistDetailKey() {
		return this.npackinglistDetailKey;
	}

	public void setNpackinglistDetailKey(final long npackinglistDetailKey) {
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenPackinglistsId)) {
			return false;
		}
		final CenPackinglistsId castOther = (CenPackinglistsId) other;

		return this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey()
				&& this.getNpackinglistDetailKey() == castOther.getNpackinglistDetailKey();
	}

	@Override
	public int hashCode() {
		int result = 19;

		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNpackinglistDetailKey();
		return result;
	}

	/** {@inheritDoc} */
	@Override
	public String asString() {
		return ToStringBuilder.reflectionToString(this);
	}

}
