package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Aug 1, 2025 12:03:08 PM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPackinglistMpId generated by hbm2java
 */
@Embeddable
public class CenPackinglistMpId  implements java.io.Serializable {


     private long npackinglistIndexKey;
     private long npackinglistDetailKey;

    public CenPackinglistMpId() {
    }

    public CenPackinglistMpId(long npackinglistIndexKey, long npackinglistDetailKey) {
       this.npackinglistIndexKey = npackinglistIndexKey;
       this.npackinglistDetailKey = npackinglistDetailKey;
    }
   


    @Column(name="NPACKINGLIST_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistIndexKey() {
        return this.npackinglistIndexKey;
    }
    
    public void setNpackinglistIndexKey(long npackinglistIndexKey) {
        this.npackinglistIndexKey = npackinglistIndexKey;
    }


    @Column(name="NPACKINGLIST_DETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistDetailKey() {
        return this.npackinglistDetailKey;
    }
    
    public void setNpackinglistDetailKey(long npackinglistDetailKey) {
        this.npackinglistDetailKey = npackinglistDetailKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenPackinglistMpId) ) return false;
		 CenPackinglistMpId castOther = ( CenPackinglistMpId ) other; 
         
		 return (this.getNpackinglistIndexKey()==castOther.getNpackinglistIndexKey())
 && (this.getNpackinglistDetailKey()==castOther.getNpackinglistDetailKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNpackinglistIndexKey();
         result = 37 * result + (int) this.getNpackinglistDetailKey();
         return result;
   }   


}


