package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 27.06.2017 08:12:25 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPictureResolutionId generated by hbm2java
 */
@Embeddable
public class CenPictureResolutionId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long npictureIndexKey;
	private int nresolution;

	public CenPictureResolutionId() {
	}

	public CenPictureResolutionId(final long npictureIndexKey, final int nresolution) {
		this.npictureIndexKey = npictureIndexKey;
		this.nresolution = nresolution;
	}

	@Column(name = "NPICTURE_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpictureIndexKey() {
		return this.npictureIndexKey;
	}

	public void setNpictureIndexKey(final long npictureIndexKey) {
		this.npictureIndexKey = npictureIndexKey;
	}

	@Column(name = "NRESOLUTION", nullable = false, precision = 2, scale = 0)
	public int getNresolution() {
		return this.nresolution;
	}

	public void setNresolution(final int nresolution) {
		this.nresolution = nresolution;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenPictureResolutionId)) {
			return false;
		}
		final CenPictureResolutionId castOther = (CenPictureResolutionId) other;

		return (this.getNpictureIndexKey() == castOther.getNpictureIndexKey())
				&& (this.getNresolution() == castOther.getNresolution());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNpictureIndexKey();
		result = 37 * result + this.getNresolution();
		return result;
	}

}
