package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jun 2, 2025 3:31:31 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPackinglistIfId generated by hbm2java
 */
@Embeddable
public class CenPackinglistIfId implements java.io.Serializable {

	private long npackinglistIndexKey;
	private long npackinglistDetailKey;

	public CenPackinglistIfId() {
	}

	public CenPackinglistIfId(long npackinglistIndexKey, long npackinglistDetailKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NPACKINGLIST_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistDetailKey() {
		return this.npackinglistDetailKey;
	}

	public void setNpackinglistDetailKey(long npackinglistDetailKey) {
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CenPackinglistIfId))
			return false;
		CenPackinglistIfId castOther = (CenPackinglistIfId) other;

		return (this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey())
				&& (this.getNpackinglistDetailKey() == castOther.getNpackinglistDetailKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNpackinglistDetailKey();
		return result;
	}

}


