package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 08.11.2021 13:40:52 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPackinglistEuAlgId generated by hbm2java
 */
@Embeddable
public class CenPackinglistEuAlgId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long npackinglistIndexKey;
     private long npackinglistDetailKey;
     private long neuAllgKey;
     private long neuRegionKey;

    public CenPackinglistEuAlgId() {
    }

    public CenPackinglistEuAlgId(long npackinglistIndexKey, long npackinglistDetailKey, long neuAllgKey, long neuRegionKey) {
       this.npackinglistIndexKey = npackinglistIndexKey;
       this.npackinglistDetailKey = npackinglistDetailKey;
       this.neuAllgKey = neuAllgKey;
       this.neuRegionKey = neuRegionKey;
    }
   


    @Column(name="NPACKINGLIST_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistIndexKey() {
        return this.npackinglistIndexKey;
    }
    
    public void setNpackinglistIndexKey(long npackinglistIndexKey) {
        this.npackinglistIndexKey = npackinglistIndexKey;
    }


    @Column(name="NPACKINGLIST_DETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistDetailKey() {
        return this.npackinglistDetailKey;
    }
    
    public void setNpackinglistDetailKey(long npackinglistDetailKey) {
        this.npackinglistDetailKey = npackinglistDetailKey;
    }


    @Column(name="NEU_ALLG_KEY", nullable=false, precision=12, scale=0)
    public long getNeuAllgKey() {
        return this.neuAllgKey;
    }
    
    public void setNeuAllgKey(long neuAllgKey) {
        this.neuAllgKey = neuAllgKey;
    }


    @Column(name="NEU_REGION_KEY", nullable=false, precision=12, scale=0)
    public long getNeuRegionKey() {
        return this.neuRegionKey;
    }
    
    public void setNeuRegionKey(long neuRegionKey) {
        this.neuRegionKey = neuRegionKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenPackinglistEuAlgId) ) return false;
		 CenPackinglistEuAlgId castOther = ( CenPackinglistEuAlgId ) other; 
         
		 return (this.getNpackinglistIndexKey()==castOther.getNpackinglistIndexKey())
 && (this.getNpackinglistDetailKey()==castOther.getNpackinglistDetailKey())
 && (this.getNeuAllgKey()==castOther.getNeuAllgKey())
 && (this.getNeuRegionKey()==castOther.getNeuRegionKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNpackinglistIndexKey();
         result = 37 * result + (int) this.getNpackinglistDetailKey();
         result = 37 * result + (int) this.getNeuAllgKey();
         result = 37 * result + (int) this.getNeuRegionKey();
         return result;
   }   


}


