/*
 * CenPictures.java
 *
 * Copyright (c) 2015-2015 Lufthansa Industry Solutions AS GmbH. All Rights Reserved.
 *
 */
package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 19.10.2015 16:15:10 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CenPictures generated by hbm2java
 */
@Entity
@Table(name = "CEN_PICTURES")
public class CenPictures implements DomainObject, java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long npictureIndexKey;
	private long npltypeKey;
	private String cclient;
	private String cpictureName;
	private String cfileName;
	private String cdescription;
	private Integer nownerId;
	private byte[] bpicture;
	private String cdocId;
	private Set<CenPackinglistPictures> cenPackinglistPictureses = new HashSet<>(0);
	private Set<CenPackinglistTypePictures> cenPackinglistTypePictureses = new HashSet<>(0);
	private Set<CenPictureResolution> cenPictureResolutions = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_CEN_PICTURES")
	@SequenceGenerator(name = "SEQ_CEN_PICTURES", sequenceName = "SEQ_CEN_PICTURES", allocationSize = 1)
	@Column(name = "NPICTURE_INDEX_KEY", unique = true, nullable = false, precision = 12, scale = 0)
	public long getNpictureIndexKey() {
		return this.npictureIndexKey;
	}

	public void setNpictureIndexKey(final long npictureIndexKey) {
		this.npictureIndexKey = npictureIndexKey;
	}

	@Column(name = "NPLTYPE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpltypeKey() {
		return this.npltypeKey;
	}

	public void setNpltypeKey(final long npltypeKey) {
		this.npltypeKey = npltypeKey;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CPICTURE_NAME", nullable = false, length = 40)
	public String getCpictureName() {
		return this.cpictureName;
	}

	public void setCpictureName(final String cpictureName) {
		this.cpictureName = cpictureName;
	}

	@Column(name = "CFILE_NAME", nullable = false, length = 100)
	public String getCfileName() {
		return this.cfileName;
	}

	public void setCfileName(final String cfileName) {
		this.cfileName = cfileName;
	}

	@Column(name = "CDESCRIPTION", length = 250)
	public String getCdescription() {
		return this.cdescription;
	}

	public void setCdescription(final String cdescription) {
		this.cdescription = cdescription;
	}

	@Column(name = "NOWNER_ID", precision = 5, scale = 0)
	public Integer getNownerId() {
		return this.nownerId;
	}

	public void setNownerId(final Integer nownerId) {
		this.nownerId = nownerId;
	}

	@Column(name = "BPICTURE")
	public byte[] getBpicture() {
		return this.bpicture;
	}

	public void setBpicture(final byte[] bpicture) {
		this.bpicture = bpicture;
	}

	@Column(name = "CDOC_ID", length = 40)
	public String getCdocId() {
		return this.cdocId;
	}

	public void setCdocId(final String cdocId) {
		this.cdocId = cdocId;
	}

	@OneToMany(mappedBy = "cenPictures")
	public Set<CenPackinglistPictures> getCenPackinglistPictureses() {
		return this.cenPackinglistPictureses;
	}

	public void setCenPackinglistPictureses(final Set<CenPackinglistPictures> cenPackinglistPictureses) {
		this.cenPackinglistPictureses = cenPackinglistPictureses;
	}

	@OneToMany(mappedBy = "cenPictures")
	public Set<CenPackinglistTypePictures> getCenPackinglistTypePictureses() {
		return this.cenPackinglistTypePictureses;
	}

	public void setCenPackinglistTypePictureses(final Set<CenPackinglistTypePictures> cenPackinglistTypePictureses) {
		this.cenPackinglistTypePictureses = cenPackinglistTypePictureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cenPictures")
	public Set<CenPictureResolution> getCenPictureResolutions() {
		return this.cenPictureResolutions;
	}

	public void setCenPictureResolutions(final Set<CenPictureResolution> cenPictureResolutions) {
		this.cenPictureResolutions = cenPictureResolutions;
	}

}
