package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 13.04.2022 09:24:43 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPriceDefSnapshotPlId generated by hbm2java
 */
@Embeddable
public class CenPriceDefSnapshotPlId  implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long npackinglistIndexKey;
     private long npackinglistDetailKey;
     private long nairlineKey;

    public CenPriceDefSnapshotPlId() {
    }

    public CenPriceDefSnapshotPlId(long npackinglistIndexKey, long npackinglistDetailKey, long nairlineKey) {
       this.npackinglistIndexKey = npackinglistIndexKey;
       this.npackinglistDetailKey = npackinglistDetailKey;
       this.nairlineKey = nairlineKey;
    }
   


    @Column(name="NPACKINGLIST_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistIndexKey() {
        return this.npackinglistIndexKey;
    }
    
    public void setNpackinglistIndexKey(long npackinglistIndexKey) {
        this.npackinglistIndexKey = npackinglistIndexKey;
    }


    @Column(name="NPACKINGLIST_DETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNpackinglistDetailKey() {
        return this.npackinglistDetailKey;
    }
    
    public void setNpackinglistDetailKey(long npackinglistDetailKey) {
        this.npackinglistDetailKey = npackinglistDetailKey;
    }


    @Column(name="NAIRLINE_KEY", nullable=false, precision=12, scale=0)
    public long getNairlineKey() {
        return this.nairlineKey;
    }
    
    public void setNairlineKey(long nairlineKey) {
        this.nairlineKey = nairlineKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenPriceDefSnapshotPlId) ) return false;
		 CenPriceDefSnapshotPlId castOther = ( CenPriceDefSnapshotPlId ) other; 
         
		 return (this.getNpackinglistIndexKey()==castOther.getNpackinglistIndexKey())
 && (this.getNpackinglistDetailKey()==castOther.getNpackinglistDetailKey())
 && (this.getNairlineKey()==castOther.getNairlineKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNpackinglistIndexKey();
         result = 37 * result + (int) this.getNpackinglistDetailKey();
         result = 37 * result + (int) this.getNairlineKey();
         return result;
   }   


}


