package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 20.09.2018 13:47:58 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPpsMealLayoutId generated by hbm2java
 */
@Embeddable
public class CenPpsMealLayoutId  implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nprodOrderKey;
     private long ncontainerKey;

    public CenPpsMealLayoutId() {
    }

    public CenPpsMealLayoutId(long nprodOrderKey, long ncontainerKey) {
       this.nprodOrderKey = nprodOrderKey;
       this.ncontainerKey = ncontainerKey;
    }
   


    @Column(name="NPROD_ORDER_KEY", nullable=false, precision=12, scale=0)
    public long getNprodOrderKey() {
        return this.nprodOrderKey;
    }
    
    public void setNprodOrderKey(long nprodOrderKey) {
        this.nprodOrderKey = nprodOrderKey;
    }


    @Column(name="NCONTAINER_KEY", nullable=false, precision=12, scale=0)
    public long getNcontainerKey() {
        return this.ncontainerKey;
    }
    
    public void setNcontainerKey(long ncontainerKey) {
        this.ncontainerKey = ncontainerKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenPpsMealLayoutId) ) return false;
		 CenPpsMealLayoutId castOther = ( CenPpsMealLayoutId ) other; 
         
		 return (this.getNprodOrderKey()==castOther.getNprodOrderKey())
 && (this.getNcontainerKey()==castOther.getNcontainerKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNprodOrderKey();
         result = 37 * result + (int) this.getNcontainerKey();
         return result;
   }   


}


