package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenPackinglistDetailId generated by hbm2java
 */
@Embeddable
public class CenPackinglistDetailId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long npackinglistIndexKey;
	private long npackinglistDetailKey;
	private long ndetailKey;
	private int nsort;

	public CenPackinglistDetailId() {
	}

	public CenPackinglistDetailId(final long npackinglistIndexKey, final long npackinglistDetailKey, final long ndetailKey,
			final int nsort) {
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.npackinglistDetailKey = npackinglistDetailKey;
		this.ndetailKey = ndetailKey;
		this.nsort = nsort;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(final long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NPACKINGLIST_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistDetailKey() {
		return this.npackinglistDetailKey;
	}

	public void setNpackinglistDetailKey(final long npackinglistDetailKey) {
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Column(name = "NDETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNdetailKey() {
		return this.ndetailKey;
	}

	public void setNdetailKey(final long ndetailKey) {
		this.ndetailKey = ndetailKey;
	}

	@Column(name = "NSORT", nullable = false, precision = 6, scale = 0)
	public int getNsort() {
		return this.nsort;
	}

	public void setNsort(final int nsort) {
		this.nsort = nsort;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenPackinglistDetailId)) {
			return false;
		}
		final CenPackinglistDetailId castOther = (CenPackinglistDetailId) other;

		return this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey()
				&& this.getNpackinglistDetailKey() == castOther.getNpackinglistDetailKey()
				&& this.getNdetailKey() == castOther.getNdetailKey()
				&& this.getNsort() == castOther.getNsort();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNpackinglistDetailKey();
		result = 37 * result + (int) this.getNdetailKey();
		result = 37 * result + this.getNsort();
		return result;
	}

}
