package com.lsgskychefs.cbase.middleware.persistence.domain;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenRequestOutPaxId generated by hbm2java
 */
@Embeddable
public class CenRequestOutPaxId
		implements com.lsgskychefs.cbase.middleware.persistence.domain.DomainObject, java.io.Serializable {

	private long njobNr;
	private int nclassNumber;

	public CenRequestOutPaxId() {
	}

	public CenRequestOutPaxId(final long njobNr, final int nclassNumber) {
		this.njobNr = njobNr;
		this.nclassNumber = nclassNumber;
	}

	@Column(name = "NJOB_NR", nullable = false, precision = 12)
	public long getNjobNr() {
		return this.njobNr;
	}

	public void setNjobNr(final long njobNr) {
		this.njobNr = njobNr;
	}

	@Column(name = "NCLASS_NUMBER", nullable = false, precision = 6)
	public int getNclassNumber() {
		return this.nclassNumber;
	}

	public void setNclassNumber(final int nclassNumber) {
		this.nclassNumber = nclassNumber;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenRequestOutPaxId)) {
			return false;
		}
		final CenRequestOutPaxId castOther = (CenRequestOutPaxId) other;

		return (this.getNjobNr() == castOther.getNjobNr()) && (this.getNclassNumber() == castOther.getNclassNumber());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNjobNr();
		result = 37 * result + this.getNclassNumber();
		return result;
	}

}
