package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 16.12.2015 15:52:07 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.lsgskychefs.cbase.middleware.persistence.constant.CenSetupKeySection;

/**
 * CenSetupId generated by hbm2java
 *
 * @see CenSetupKeySection
 */
@Embeddable
public class CenSetupId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String cclient;

	private String csection;

	private String ckey;

	public CenSetupId() {
	}

	public CenSetupId(final String cclient, final String csection, final String ckey) {
		this.cclient = cclient;
		this.csection = csection;
		this.ckey = ckey;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CSECTION", nullable = false, length = 25)
	public String getCsection() {
		return this.csection;
	}

	public void setCsection(final String csection) {
		this.csection = csection;
	}

	@Column(name = "CKEY", nullable = false, length = 25)
	public String getCkey() {
		return this.ckey;
	}

	public void setCkey(final String ckey) {
		this.ckey = ckey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenSetupId)) {
			return false;
		}
		final CenSetupId castOther = (CenSetupId) other;

		return (this.getCclient() == castOther.getCclient()
				|| this.getCclient() != null && castOther.getCclient() != null && this.getCclient().equals(castOther.getCclient()))
				&& (this.getCsection() == castOther.getCsection() || this.getCsection() != null && castOther.getCsection() != null
						&& this.getCsection().equals(castOther.getCsection()))
				&& (this.getCkey() == castOther.getCkey()
						|| this.getCkey() != null && castOther.getCkey() != null && this.getCkey().equals(castOther.getCkey()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCclient() == null ? 0 : this.getCclient().hashCode());
		result = 37 * result + (getCsection() == null ? 0 : this.getCsection().hashCode());
		result = 37 * result + (getCkey() == null ? 0 : this.getCkey().hashCode());
		return result;
	}

}
