package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Mar 17, 2017 10:39:57 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenSlsProjConcAttId generated by hbm2java
 */
@Embeddable
public class CenSlsProjConcAttId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nprojConceptKey;
	private long nattachmentKey;

	public CenSlsProjConcAttId() {
	}

	public CenSlsProjConcAttId(final long nprojConceptKey, final long nattachmentKey) {
		this.nprojConceptKey = nprojConceptKey;
		this.nattachmentKey = nattachmentKey;
	}

	@Column(name = "NPROJ_CONCEPT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNprojConceptKey() {
		return this.nprojConceptKey;
	}

	public void setNprojConceptKey(final long nprojConceptKey) {
		this.nprojConceptKey = nprojConceptKey;
	}

	@Column(name = "NATTACHMENT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNattachmentKey() {
		return this.nattachmentKey;
	}

	public void setNattachmentKey(final long nattachmentKey) {
		this.nattachmentKey = nattachmentKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenSlsProjConcAttId)) {
			return false;
		}
		final CenSlsProjConcAttId castOther = (CenSlsProjConcAttId) other;

		return (this.getNprojConceptKey() == castOther.getNprojConceptKey())
				&& (this.getNattachmentKey() == castOther.getNattachmentKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNprojConceptKey();
		result = 37 * result + (int) this.getNattachmentKey();
		return result;
	}

}
