package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 10.03.2017 10:38:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenSlsProjFreetextId generated by hbm2java
 */
@Embeddable
public class CenSlsProjFreetextId implements java.io.Serializable {

	/** serial versionUID */
	private static final long serialVersionUID = 1L;

	private long nprojectKey;
	private long nprojKwCatKey;

	@Column(name = "NPROJECT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNprojectKey() {
		return this.nprojectKey;
	}

	public void setNprojectKey(final long nprojectKey) {
		this.nprojectKey = nprojectKey;
	}

	@Column(name = "NPROJ_KW_CAT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNprojKwCatKey() {
		return this.nprojKwCatKey;
	}

	public void setNprojKwCatKey(final long nprojKwCatKey) {
		this.nprojKwCatKey = nprojKwCatKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenSlsProjFreetextId)) {
			return false;
		}
		final CenSlsProjFreetextId castOther = (CenSlsProjFreetextId) other;

		return (this.getNprojectKey() == castOther.getNprojectKey())
				&& (this.getNprojKwCatKey() == castOther.getNprojKwCatKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNprojectKey();
		result = 37 * result + (int) this.getNprojKwCatKey();
		return result;
	}

}
