package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 28.02.2017 11:41:38 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenSlsProjConceptKpiId generated by hbm2java
 */
@Embeddable
public class CenSlsProjConceptKpiId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nprojConceptKey;
	private long nprojKpiKey;

	@Column(name = "NPROJ_CONCEPT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNprojConceptKey() {
		return this.nprojConceptKey;
	}

	public void setNprojConceptKey(final long nprojConceptKey) {
		this.nprojConceptKey = nprojConceptKey;
	}

	@Column(name = "NPROJ_KPI_KEY", nullable = false, precision = 12, scale = 0)
	public long getNprojKpiKey() {
		return this.nprojKpiKey;
	}

	public void setNprojKpiKey(final long nprojKpiKey) {
		this.nprojKpiKey = nprojKpiKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof CenSlsProjConceptKpiId)) {
			return false;
		}
		final CenSlsProjConceptKpiId castOther = (CenSlsProjConceptKpiId) other;

		return (this.getNprojConceptKey() == castOther.getNprojConceptKey())
				&& (this.getNprojKpiKey() == castOther.getNprojKpiKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNprojConceptKey();
		result = 37 * result + (int) this.getNprojKpiKey();
		return result;
	}

}
