package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 08.06.2016 11:23:54 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CenWebLabelsId generated by hbm2java
 */
@Embeddable
public class CenWebLabelsId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String cflightKey;
	private String cuser;
	private long nsort;

	public CenWebLabelsId() {
	}

	public CenWebLabelsId(final String cflightKey, final String cuser, final long nsort) {
		this.cflightKey = cflightKey;
		this.cuser = cuser;
		this.nsort = nsort;
	}

	@Column(name = "CFLIGHT_KEY", nullable = false, length = 25)
	public String getCflightKey() {
		return this.cflightKey;
	}

	public void setCflightKey(final String cflightKey) {
		this.cflightKey = cflightKey;
	}

	@Column(name = "CUSER", nullable = false, length = 15)
	public String getCuser() {
		return this.cuser;
	}

	public void setCuser(final String cuser) {
		this.cuser = cuser;
	}

	@Column(name = "NSORT", nullable = false, precision = 12, scale = 0)
	public long getNsort() {
		return this.nsort;
	}

	public void setNsort(final long nsort) {
		this.nsort = nsort;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof CenWebLabelsId)) {
			return false;
		}
		final CenWebLabelsId castOther = (CenWebLabelsId) other;

		return (this.getCflightKey() == castOther.getCflightKey() || this.getCflightKey() != null && castOther.getCflightKey() != null
				&& this.getCflightKey().equals(castOther.getCflightKey()))
				&& (this.getCuser() == castOther.getCuser()
						|| this.getCuser() != null && castOther.getCuser() != null && this.getCuser().equals(castOther.getCuser()))
				&& this.getNsort() == castOther.getNsort();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCflightKey() == null ? 0 : this.getCflightKey().hashCode());
		result = 37 * result + (getCuser() == null ? 0 : this.getCuser().hashCode());
		result = 37 * result + (int) this.getNsort();
		return result;
	}

}
