package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 14.07.2021 14:08:48 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocClassForecastId generated by hbm2java
 */
@Embeddable
public class LocClassForecastId implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    private String cunit;
    private long nairlineKey;
    private String cclass;
    private long nroutingId;
    private Date dvalidFrom;
    private String ctimeFrom;

    public LocClassForecastId() {
    }

    public LocClassForecastId(String cunit, long nairlineKey, String cclass, long nroutingId, Date dvalidFrom, String ctimeFrom) {
        this.cunit = cunit;
        this.nairlineKey = nairlineKey;
        this.cclass = cclass;
        this.nroutingId = nroutingId;
        this.dvalidFrom = dvalidFrom;
        this.ctimeFrom = ctimeFrom;
    }


    @Column(name = "CUNIT", nullable = false, length = 4)
    public String getCunit() {
        return this.cunit;
    }

    public void setCunit(String cunit) {
        this.cunit = cunit;
    }


    @Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
    public long getNairlineKey() {
        return this.nairlineKey;
    }

    public void setNairlineKey(long nairlineKey) {
        this.nairlineKey = nairlineKey;
    }


    @Column(name = "CCLASS", nullable = false, length = 10)
    public String getCclass() {
        return this.cclass;
    }

    public void setCclass(String cclass) {
        this.cclass = cclass;
    }


    @Column(name = "NROUTING_ID", nullable = false, precision = 12, scale = 0)
    public long getNroutingId() {
        return this.nroutingId;
    }

    public void setNroutingId(long nroutingId) {
        this.nroutingId = nroutingId;
    }


    @Column(name = "DVALID_FROM", nullable = false, length = 7)
    public Date getDvalidFrom() {
        return this.dvalidFrom;
    }

    public void setDvalidFrom(Date dvalidFrom) {
        this.dvalidFrom = dvalidFrom;
    }


    @Column(name = "CTIME_FROM", nullable = false, length = 5)
    public String getCtimeFrom() {
        return this.ctimeFrom;
    }

    public void setCtimeFrom(String ctimeFrom) {
        this.ctimeFrom = ctimeFrom;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof LocClassForecastId)) return false;
        LocClassForecastId castOther = (LocClassForecastId) other;

        return ((this.getCunit() == castOther.getCunit()) || (this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit())))
                && (this.getNairlineKey() == castOther.getNairlineKey())
                && ((this.getCclass() == castOther.getCclass()) || (this.getCclass() != null && castOther.getCclass() != null && this.getCclass().equals(castOther.getCclass())))
                && (this.getNroutingId() == castOther.getNroutingId())
                && ((this.getDvalidFrom() == castOther.getDvalidFrom()) || (this.getDvalidFrom() != null && castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom())))
                && ((this.getCtimeFrom() == castOther.getCtimeFrom()) || (this.getCtimeFrom() != null && castOther.getCtimeFrom() != null && this.getCtimeFrom().equals(castOther.getCtimeFrom())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
        result = 37 * result + (int) this.getNairlineKey();
        result = 37 * result + (getCclass() == null ? 0 : this.getCclass().hashCode());
        result = 37 * result + (int) this.getNroutingId();
        result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
        result = 37 * result + (getCtimeFrom() == null ? 0 : this.getCtimeFrom().hashCode());
        return result;
    }


}


