package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jan 19, 2017 12:23:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocOperationsId generated by hbm2java
 */
@Embeddable
public class LocOperationsId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String cclient;
	private String cunit;
	private String ctext;

	public LocOperationsId() {
	}

	public LocOperationsId(final String cclient, final String cunit, final String ctext) {
		this.cclient = cclient;
		this.cunit = cunit;
		this.ctext = ctext;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "CTEXT", nullable = false, length = 20)
	public String getCtext() {
		return this.ctext;
	}

	public void setCtext(final String ctext) {
		this.ctext = ctext;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof LocOperationsId)) {
			return false;
		}
		final LocOperationsId castOther = (LocOperationsId) other;

		return ((this.getCclient() == castOther.getCclient())
				|| (this.getCclient() != null && castOther.getCclient() != null && this.getCclient().equals(castOther.getCclient())))
				&& ((this.getCunit() == castOther.getCunit())
						|| (this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit())))
				&& ((this.getCtext() == castOther.getCtext())
						|| (this.getCtext() != null && castOther.getCtext() != null && this.getCtext().equals(castOther.getCtext())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCclient() == null ? 0 : this.getCclient().hashCode());
		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		result = 37 * result + (getCtext() == null ? 0 : this.getCtext().hashCode());
		return result;
	}

}
