package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jul 3, 2018 4:59:37 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocPloWsShiftBreakId generated by hbm2java
 */
@Embeddable
public class LocPloWsShiftBreakId implements java.io.Serializable {

	/** serial versionUID */
	private static final long serialVersionUID = 1L;

	private long nworkstationKey;
	private long nshiftKey;
	private long nbreakKey;

	public LocPloWsShiftBreakId() {
	}

	public LocPloWsShiftBreakId(final long nworkstationKey, final long nshiftKey, final long nbreakKey) {
		this.nworkstationKey = nworkstationKey;
		this.nshiftKey = nshiftKey;
		this.nbreakKey = nbreakKey;
	}

	@Column(name = "NWORKSTATION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNworkstationKey() {
		return this.nworkstationKey;
	}

	public void setNworkstationKey(final long nworkstationKey) {
		this.nworkstationKey = nworkstationKey;
	}

	@Column(name = "NSHIFT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNshiftKey() {
		return this.nshiftKey;
	}

	public void setNshiftKey(final long nshiftKey) {
		this.nshiftKey = nshiftKey;
	}

	@Column(name = "NBREAK_KEY", nullable = false, precision = 12, scale = 0)
	public long getNbreakKey() {
		return this.nbreakKey;
	}

	public void setNbreakKey(final long nbreakKey) {
		this.nbreakKey = nbreakKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocPloWsShiftBreakId)) {
			return false;
		}
		final LocPloWsShiftBreakId castOther = (LocPloWsShiftBreakId) other;

		return (this.getNworkstationKey() == castOther.getNworkstationKey())
				&& (this.getNshiftKey() == castOther.getNshiftKey())
				&& (this.getNbreakKey() == castOther.getNbreakKey());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNworkstationKey();
		result = 37 * result + (int) this.getNshiftKey();
		result = 37 * result + (int) this.getNbreakKey();
		return result;
	}

}
