package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Oct 10, 2019 12:14:52 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocPlSubstFlightsId generated by hbm2java
 */
@Embeddable
public class LocPlSubstFlightsId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nlocPlSubstKey;
	private long nresultKey;
	private long nplIndexKey;

	public LocPlSubstFlightsId() {
	}

	public LocPlSubstFlightsId(final long nlocPlSubstKey, final long nresultKey, final long nplIndexKey) {
		this.nlocPlSubstKey = nlocPlSubstKey;
		this.nresultKey = nresultKey;
		this.nplIndexKey = nplIndexKey;
	}

	@Column(name = "NLOC_PL_SUBST_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlocPlSubstKey() {
		return this.nlocPlSubstKey;
	}

	public void setNlocPlSubstKey(final long nlocPlSubstKey) {
		this.nlocPlSubstKey = nlocPlSubstKey;
	}

	@Column(name = "NRESULT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNresultKey() {
		return this.nresultKey;
	}

	public void setNresultKey(final long nresultKey) {
		this.nresultKey = nresultKey;
	}

	@Column(name = "NPL_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNplIndexKey() {
		return this.nplIndexKey;
	}

	public void setNplIndexKey(final long nplIndexKey) {
		this.nplIndexKey = nplIndexKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocPlSubstFlightsId)) {
			return false;
		}
		final LocPlSubstFlightsId castOther = (LocPlSubstFlightsId) other;

		return (this.getNlocPlSubstKey() == castOther.getNlocPlSubstKey())
				&& (this.getNresultKey() == castOther.getNresultKey())
				&& (this.getNplIndexKey() == castOther.getNplIndexKey());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNlocPlSubstKey();
		result = 37 * result + (int) this.getNresultKey();
		result = 37 * result + (int) this.getNplIndexKey();
		return result;
	}

}
