package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 18.01.2019 10:58:33 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocPloWsShiftId generated by hbm2java
 */
@Embeddable
public class LocPloWsShiftId  implements java.io.Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nworkstationKey;
     private long nshiftKey;

    public LocPloWsShiftId() {
    }

    public LocPloWsShiftId(long nworkstationKey, long nshiftKey) {
       this.nworkstationKey = nworkstationKey;
       this.nshiftKey = nshiftKey;
    }
   


    @Column(name="NWORKSTATION_KEY", nullable=false, precision=12, scale=0)
    public long getNworkstationKey() {
        return this.nworkstationKey;
    }
    
    public void setNworkstationKey(long nworkstationKey) {
        this.nworkstationKey = nworkstationKey;
    }


    @Column(name="NSHIFT_KEY", nullable=false, precision=12, scale=0)
    public long getNshiftKey() {
        return this.nshiftKey;
    }
    
    public void setNshiftKey(long nshiftKey) {
        this.nshiftKey = nshiftKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocPloWsShiftId) ) return false;
		 LocPloWsShiftId castOther = ( LocPloWsShiftId ) other; 
         
		 return (this.getNworkstationKey()==castOther.getNworkstationKey())
 && (this.getNshiftKey()==castOther.getNshiftKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNworkstationKey();
         result = 37 * result + (int) this.getNshiftKey();
         return result;
   }   


}


