package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 31.03.2016 13:37:22 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocSetupId generated by hbm2java
 */
@Embeddable
public class LocSetupId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nuserId;

	private String csection;

	private String ckey;

	public LocSetupId() {
	}

	public LocSetupId(final long nuserId, final String csection, final String ckey) {
		this.nuserId = nuserId;
		this.csection = csection;
		this.ckey = ckey;
	}

	@Column(name = "NUSER_ID", nullable = false, precision = 12, scale = 0)
	public long getNuserId() {
		return this.nuserId;
	}

	public void setNuserId(final long nuserId) {
		this.nuserId = nuserId;
	}

	@Column(name = "CSECTION", nullable = false, length = 25)
	public String getCsection() {
		return this.csection;
	}

	public void setCsection(final String csection) {
		this.csection = csection;
	}

	@Column(name = "CKEY", nullable = false, length = 256)
	public String getCkey() {
		return this.ckey;
	}

	public void setCkey(final String ckey) {
		this.ckey = ckey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocSetupId)) {
			return false;
		}
		final LocSetupId castOther = (LocSetupId) other;

		return this.getNuserId() == castOther.getNuserId()
				&& (this.getCsection() == castOther.getCsection() || this.getCsection() != null && castOther.getCsection() != null
						&& this.getCsection().equals(castOther.getCsection()))
				&& (this.getCkey() == castOther.getCkey()
						|| this.getCkey() != null && castOther.getCkey() != null && this.getCkey().equals(castOther.getCkey()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + Long.hashCode(this.getNuserId());
		result = 37 * result + (getCsection() == null ? 0 : this.getCsection().hashCode());
		result = 37 * result + (getCkey() == null ? 0 : this.getCkey().hashCode());
		return result;
	}

}
