package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitTimesFlightId generated by hbm2java
 */
@Embeddable
public class LocUnitTimesFlightId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private String cclient;
	private String cunit;
	private long nairlineKey;
	private long nflightNumber;
	private String csuffix;

	public LocUnitTimesFlightId() {
	}

	public LocUnitTimesFlightId(final String cclient, final String cunit, final long nairlineKey, final long nflightNumber,
			final String csuffix) {
		this.cclient = cclient;
		this.cunit = cunit;
		this.nairlineKey = nairlineKey;
		this.nflightNumber = nflightNumber;
		this.csuffix = csuffix;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Column(name = "NFLIGHT_NUMBER", nullable = false, precision = 12, scale = 0)
	public long getNflightNumber() {
		return this.nflightNumber;
	}

	public void setNflightNumber(final long nflightNumber) {
		this.nflightNumber = nflightNumber;
	}

	@Column(name = "CSUFFIX", nullable = false, length = 1)
	public String getCsuffix() {
		return this.csuffix;
	}

	public void setCsuffix(final String csuffix) {
		this.csuffix = csuffix;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitTimesFlightId)) {
			return false;
		}
		final LocUnitTimesFlightId castOther = (LocUnitTimesFlightId) other;

		return (this.getCclient() == castOther.getCclient()
				|| this.getCclient() != null && castOther.getCclient() != null && this.getCclient().equals(castOther.getCclient()))
				&& (this.getCunit() == castOther.getCunit()
						|| this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit()))
				&& this.getNairlineKey() == castOther.getNairlineKey()
				&& this.getNflightNumber() == castOther.getNflightNumber()
				&& (this.getCsuffix() == castOther.getCsuffix() || this.getCsuffix() != null && castOther.getCsuffix() != null
						&& this.getCsuffix().equals(castOther.getCsuffix()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCclient() == null ? 0 : this.getCclient().hashCode());
		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		result = 37 * result + (int) this.getNairlineKey();
		result = 37 * result + (int) this.getNflightNumber();
		result = 37 * result + (getCsuffix() == null ? 0 : this.getCsuffix().hashCode());
		return result;
	}

}
