package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitSetupId generated by hbm2java
 */
@Embeddable
public class LocUnitSetupId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private String cunit;
	private String csection;
	private String ckey;

	public LocUnitSetupId() {
	}

	public LocUnitSetupId(final String cunit, final String csection, final String ckey) {
		this.cunit = cunit;
		this.csection = csection;
		this.ckey = ckey;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "CSECTION", nullable = false, length = 60)
	public String getCsection() {
		return this.csection;
	}

	public void setCsection(final String csection) {
		this.csection = csection;
	}

	@Column(name = "CKEY", nullable = false, length = 60)
	public String getCkey() {
		return this.ckey;
	}

	public void setCkey(final String ckey) {
		this.ckey = ckey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitSetupId)) {
			return false;
		}
		final LocUnitSetupId castOther = (LocUnitSetupId) other;

		return (this.getCunit() == castOther.getCunit()
				|| this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit()))
				&& (this.getCsection() == castOther.getCsection() || this.getCsection() != null && castOther.getCsection() != null
						&& this.getCsection().equals(castOther.getCsection()))
				&& (this.getCkey() == castOther.getCkey()
						|| this.getCkey() != null && castOther.getCkey() != null && this.getCkey().equals(castOther.getCkey()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		result = 37 * result + (getCsection() == null ? 0 : this.getCsection().hashCode());
		result = 37 * result + (getCkey() == null ? 0 : this.getCkey().hashCode());
		return result;
	}

}
