package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitCheckptMateId generated by hbm2java
 */
@Embeddable
public class LocUnitCheckptMateId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long ncheckpointKey;
	private long ncheckpointMateKey;

	public LocUnitCheckptMateId() {
	}

	public LocUnitCheckptMateId(final long ncheckpointKey, final long ncheckpointMateKey) {
		this.ncheckpointKey = ncheckpointKey;
		this.ncheckpointMateKey = ncheckpointMateKey;
	}

	@Column(name = "NCHECKPOINT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcheckpointKey() {
		return this.ncheckpointKey;
	}

	public void setNcheckpointKey(final long ncheckpointKey) {
		this.ncheckpointKey = ncheckpointKey;
	}

	@Column(name = "NCHECKPOINT_MATE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcheckpointMateKey() {
		return this.ncheckpointMateKey;
	}

	public void setNcheckpointMateKey(final long ncheckpointMateKey) {
		this.ncheckpointMateKey = ncheckpointMateKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitCheckptMateId)) {
			return false;
		}
		final LocUnitCheckptMateId castOther = (LocUnitCheckptMateId) other;

		return this.getNcheckpointKey() == castOther.getNcheckpointKey()
				&& this.getNcheckpointMateKey() == castOther.getNcheckpointMateKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNcheckpointKey();
		result = 37 * result + (int) this.getNcheckpointMateKey();
		return result;
	}

}
