package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitPlFlightLabelId generated by hbm2java
 */
@Embeddable
public class LocUnitPlFlightLabelId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nplAreaKey;
	private long nworkstationKey;

	public LocUnitPlFlightLabelId() {
	}

	public LocUnitPlFlightLabelId(final long nplAreaKey, final long nworkstationKey) {
		this.nplAreaKey = nplAreaKey;
		this.nworkstationKey = nworkstationKey;
	}

	@Column(name = "NPL_AREA_KEY", nullable = false, precision = 12, scale = 0)
	public long getNplAreaKey() {
		return this.nplAreaKey;
	}

	public void setNplAreaKey(final long nplAreaKey) {
		this.nplAreaKey = nplAreaKey;
	}

	@Column(name = "NWORKSTATION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNworkstationKey() {
		return this.nworkstationKey;
	}

	public void setNworkstationKey(final long nworkstationKey) {
		this.nworkstationKey = nworkstationKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitPlFlightLabelId)) {
			return false;
		}
		final LocUnitPlFlightLabelId castOther = (LocUnitPlFlightLabelId) other;

		return this.getNplAreaKey() == castOther.getNplAreaKey()
				&& this.getNworkstationKey() == castOther.getNworkstationKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNplAreaKey();
		result = 37 * result + (int) this.getNworkstationKey();
		return result;
	}

}
