package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Sep 15, 2016 12:40:57 PM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitCheckptPriorId generated by hbm2java
 */
@Embeddable
public class LocUnitCheckptPriorId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long ncheckpointKey;
	private long ncheckpointPriorKey;
	private Date dvalidfrom;

	public LocUnitCheckptPriorId() {
	}

	public LocUnitCheckptPriorId(final long ncheckpointKey, final long ncheckpointPriorKey, final Date dvalidfrom) {
		this.ncheckpointKey = ncheckpointKey;
		this.ncheckpointPriorKey = ncheckpointPriorKey;
		this.dvalidfrom = dvalidfrom;
	}

	@Column(name = "NCHECKPOINT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcheckpointKey() {
		return this.ncheckpointKey;
	}

	public void setNcheckpointKey(final long ncheckpointKey) {
		this.ncheckpointKey = ncheckpointKey;
	}

	@Column(name = "NCHECKPOINT_PRIOR_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcheckpointPriorKey() {
		return this.ncheckpointPriorKey;
	}

	public void setNcheckpointPriorKey(final long ncheckpointPriorKey) {
		this.ncheckpointPriorKey = ncheckpointPriorKey;
	}

	@Column(name = "DVALIDFROM", nullable = false, length = 7)
	public Date getDvalidfrom() {
		return this.dvalidfrom;
	}

	public void setDvalidfrom(final Date dvalidfrom) {
		this.dvalidfrom = dvalidfrom;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof LocUnitCheckptPriorId)) {
			return false;
		}
		final LocUnitCheckptPriorId castOther = (LocUnitCheckptPriorId) other;

		return (this.getNcheckpointKey() == castOther.getNcheckpointKey())
				&& (this.getNcheckpointPriorKey() == castOther.getNcheckpointPriorKey())
				&& ((this.getDvalidfrom() == castOther.getDvalidfrom()) || (this.getDvalidfrom() != null
						&& castOther.getDvalidfrom() != null && this.getDvalidfrom().equals(castOther.getDvalidfrom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNcheckpointKey();
		result = 37 * result + (int) this.getNcheckpointPriorKey();
		result = 37 * result + (getDvalidfrom() == null ? 0 : this.getDvalidfrom().hashCode());
		return result;
	}

}
