package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitLabelAreaId generated by hbm2java
 */
@Embeddable
public class LocUnitLabelAreaId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nworkstationKey;
	private long nlabelGroupKey;
	private Date dvalidFrom;

	public LocUnitLabelAreaId() {
	}

	public LocUnitLabelAreaId(final long nworkstationKey, final long nlabelGroupKey, final Date dvalidFrom) {
		this.nworkstationKey = nworkstationKey;
		this.nlabelGroupKey = nlabelGroupKey;
		this.dvalidFrom = dvalidFrom;
	}

	@Column(name = "NWORKSTATION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNworkstationKey() {
		return this.nworkstationKey;
	}

	public void setNworkstationKey(final long nworkstationKey) {
		this.nworkstationKey = nworkstationKey;
	}

	@Column(name = "NLABEL_GROUP_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlabelGroupKey() {
		return this.nlabelGroupKey;
	}

	public void setNlabelGroupKey(final long nlabelGroupKey) {
		this.nlabelGroupKey = nlabelGroupKey;
	}

	@Column(name = "DVALID_FROM", nullable = false, length = 7)
	public Date getDvalidFrom() {
		return this.dvalidFrom;
	}

	public void setDvalidFrom(final Date dvalidFrom) {
		this.dvalidFrom = dvalidFrom;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitLabelAreaId)) {
			return false;
		}
		final LocUnitLabelAreaId castOther = (LocUnitLabelAreaId) other;

		return this.getNworkstationKey() == castOther.getNworkstationKey()
				&& this.getNlabelGroupKey() == castOther.getNlabelGroupKey()
				&& (this.getDvalidFrom() == castOther.getDvalidFrom() || this.getDvalidFrom() != null
						&& castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNworkstationKey();
		result = 37 * result + (int) this.getNlabelGroupKey();
		result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
		return result;
	}

}
