package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitTimesBbId generated by hbm2java
 */
@Embeddable
public class LocUnitTimesBbId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private String cclient;
	private String cunit;
	private long nairlineKey;
	private Date dvalidFrom;

	public LocUnitTimesBbId() {
	}

	public LocUnitTimesBbId(final String cclient, final String cunit, final long nairlineKey, final Date dvalidFrom) {
		this.cclient = cclient;
		this.cunit = cunit;
		this.nairlineKey = nairlineKey;
		this.dvalidFrom = dvalidFrom;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Column(name = "DVALID_FROM", nullable = false, length = 7)
	public Date getDvalidFrom() {
		return this.dvalidFrom;
	}

	public void setDvalidFrom(final Date dvalidFrom) {
		this.dvalidFrom = dvalidFrom;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitTimesBbId)) {
			return false;
		}
		final LocUnitTimesBbId castOther = (LocUnitTimesBbId) other;

		return (this.getCclient() == castOther.getCclient()
				|| this.getCclient() != null && castOther.getCclient() != null && this.getCclient().equals(castOther.getCclient()))
				&& (this.getCunit() == castOther.getCunit()
						|| this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit()))
				&& this.getNairlineKey() == castOther.getNairlineKey()
				&& (this.getDvalidFrom() == castOther.getDvalidFrom() || this.getDvalidFrom() != null
						&& castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCclient() == null ? 0 : this.getCclient().hashCode());
		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		result = 37 * result + (int) this.getNairlineKey();
		result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
		return result;
	}

}
