package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitTimesId generated by hbm2java
 */
@Embeddable
public class LocUnitTimesId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private String cclient;
	private String cunit;
	private long nairlineKey;
	private long nroutingId;
	private String cfrom;

	public LocUnitTimesId() {
	}

	public LocUnitTimesId(final String cclient, final String cunit, final long nairlineKey, final long nroutingId, final String cfrom) {
		this.cclient = cclient;
		this.cunit = cunit;
		this.nairlineKey = nairlineKey;
		this.nroutingId = nroutingId;
		this.cfrom = cfrom;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Column(name = "NROUTING_ID", nullable = false, precision = 12, scale = 0)
	public long getNroutingId() {
		return this.nroutingId;
	}

	public void setNroutingId(final long nroutingId) {
		this.nroutingId = nroutingId;
	}

	@Column(name = "CFROM", nullable = false, length = 5)
	public String getCfrom() {
		return this.cfrom;
	}

	public void setCfrom(final String cfrom) {
		this.cfrom = cfrom;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof LocUnitTimesId)) {
			return false;
		}
		final LocUnitTimesId castOther = (LocUnitTimesId) other;

		return (this.getCclient() == castOther.getCclient()
				|| this.getCclient() != null && castOther.getCclient() != null && this.getCclient().equals(castOther.getCclient()))
				&& (this.getCunit() == castOther.getCunit()
						|| this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit()))
				&& this.getNairlineKey() == castOther.getNairlineKey()
				&& this.getNroutingId() == castOther.getNroutingId()
				&& (this.getCfrom() == castOther.getCfrom()
						|| this.getCfrom() != null && castOther.getCfrom() != null && this.getCfrom().equals(castOther.getCfrom()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCclient() == null ? 0 : this.getCclient().hashCode());
		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		result = 37 * result + (int) this.getNairlineKey();
		result = 37 * result + (int) this.getNroutingId();
		result = 37 * result + (getCfrom() == null ? 0 : this.getCfrom().hashCode());
		return result;
	}

}
