package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Dec 19, 2018 2:28:25 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitGroupRangesId generated by hbm2java
 */
@Embeddable
public class LocUnitGroupRangesId extends AbstractDomainObjectPK implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nrangeKey;
	private long nlabelGroupKey;

	public LocUnitGroupRangesId() {
	}

	public LocUnitGroupRangesId(final long nrangeKey, final long nlabelGroupKey) {
		this.nrangeKey = nrangeKey;
		this.nlabelGroupKey = nlabelGroupKey;
	}

	@Column(name = "NRANGE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNrangeKey() {
		return this.nrangeKey;
	}

	public void setNrangeKey(final long nrangeKey) {
		this.nrangeKey = nrangeKey;
	}

	@Column(name = "NLABEL_GROUP_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlabelGroupKey() {
		return this.nlabelGroupKey;
	}

	public void setNlabelGroupKey(final long nlabelGroupKey) {
		this.nlabelGroupKey = nlabelGroupKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof LocUnitGroupRangesId)) {
			return false;
		}
		final LocUnitGroupRangesId castOther = (LocUnitGroupRangesId) other;

		return (this.getNrangeKey() == castOther.getNrangeKey())
				&& (this.getNlabelGroupKey() == castOther.getNlabelGroupKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNrangeKey();
		result = 37 * result + (int) this.getNlabelGroupKey();
		return result;
	}

}
