package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 18.03.2024 16:20:08 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitCheckptWorkstationsId generated by hbm2java
 */
@Embeddable
public class LocUnitCheckptWorkstationsId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long ncheckpointKey;
	private long nworkstationKey;
	private Date dvalidfrom;

	public LocUnitCheckptWorkstationsId() {
	}

	public LocUnitCheckptWorkstationsId(long ncheckpointKey, long nworkstationKey, Date dvalidfrom) {
		this.ncheckpointKey = ncheckpointKey;
		this.nworkstationKey = nworkstationKey;
		this.dvalidfrom = dvalidfrom;
	}

	@Column(name = "NCHECKPOINT_KEY", nullable = false, precision = 12, scale = 0)
	public long getNcheckpointKey() {
		return this.ncheckpointKey;
	}

	public void setNcheckpointKey(long ncheckpointKey) {
		this.ncheckpointKey = ncheckpointKey;
	}

	@Column(name = "NWORKSTATION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNworkstationKey() {
		return this.nworkstationKey;
	}

	public void setNworkstationKey(long nworkstationKey) {
		this.nworkstationKey = nworkstationKey;
	}

	@Column(name = "DVALIDFROM", nullable = false, length = 7)
	public Date getDvalidfrom() {
		return this.dvalidfrom;
	}

	public void setDvalidfrom(Date dvalidfrom) {
		this.dvalidfrom = dvalidfrom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocUnitCheckptWorkstationsId))
			return false;
		LocUnitCheckptWorkstationsId castOther = (LocUnitCheckptWorkstationsId) other;

		return (this.getNcheckpointKey() == castOther.getNcheckpointKey())
				&& (this.getNworkstationKey() == castOther.getNworkstationKey())
				&& ((this.getDvalidfrom() == castOther.getDvalidfrom()) || (this.getDvalidfrom() != null && castOther.getDvalidfrom() != null && this.getDvalidfrom()
				.equals(castOther.getDvalidfrom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNcheckpointKey();
		result = 37 * result + (int) this.getNworkstationKey();
		result = 37 * result + (getDvalidfrom() == null ? 0 : this.getDvalidfrom().hashCode());
		return result;
	}

}


