/*
 * Copyright (c) 2015-2023 Lufthansa Industry Solutions AS GmbH. All Rights Reserved.
 *
 */
package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 20-Nov-2024 14:35:02 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitStowageBoxId generated by hbm2java
 */
@Embeddable
public class LocUnitStowageBoxId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String cunit;
	private long nstowageKey;

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "NSTOWAGE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNstowageKey() {
		return this.nstowageKey;
	}

	public void setNstowageKey(long nstowageKey) {
		this.nstowageKey = nstowageKey;
	}

}


