package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jun 22, 2018 4:13:29 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitWsSchedIncreaseId generated by hbm2java
 */
@Embeddable
public class LocUnitWsSchedIncreaseId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nworkstationKey;
	private long nvalidIndex;

	@Column(name = "NWORKSTATION_KEY", nullable = false, precision = 12, scale = 0)
	public long getNworkstationKey() {
		return this.nworkstationKey;
	}

	public void setNworkstationKey(final long nworkstationKey) {
		this.nworkstationKey = nworkstationKey;
	}

	@Column(name = "NVALID_INDEX", nullable = false, precision = 12, scale = 0)
	public long getNvalidIndex() {
		return this.nvalidIndex;
	}

	public void setNvalidIndex(final long nvalidIndex) {
		this.nvalidIndex = nvalidIndex;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof LocUnitWsSchedIncreaseId)) {
			return false;
		}
		final LocUnitWsSchedIncreaseId castOther = (LocUnitWsSchedIncreaseId) other;

		return (this.getNworkstationKey() == castOther.getNworkstationKey())
				&& (this.getNvalidIndex() == castOther.getNvalidIndex());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNworkstationKey();
		result = 37 * result + (int) this.getNvalidIndex();
		return result;
	}

}
