package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Jun 8, 2022 6:35:04 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocUnitWsScheduleOffsetId generated by hbm2java
 */
@Embeddable
public class LocUnitWsScheduleOffsetId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nworkscheduleIndex;
	private int noffset;

	public LocUnitWsScheduleOffsetId() {
	}

	public LocUnitWsScheduleOffsetId(final long nworkscheduleIndex, final int noffset) {
		this.nworkscheduleIndex = nworkscheduleIndex;
		this.noffset = noffset;
	}

	@Column(name = "NWORKSCHEDULE_INDEX", nullable = false, precision = 12, scale = 0)
	public long getNworkscheduleIndex() {
		return this.nworkscheduleIndex;
	}

	public void setNworkscheduleIndex(final long nworkscheduleIndex) {
		this.nworkscheduleIndex = nworkscheduleIndex;
	}

	@Column(name = "NOFFSET", nullable = false, precision = 3, scale = 0)
	public int getNoffset() {
		return this.noffset;
	}

	public void setNoffset(final int noffset) {
		this.noffset = noffset;
	}

}
