package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 31.08.2018 08:21:00 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RobEventProductId generated by hbm2java
 */
@Embeddable
public class RobEventProductId  implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long neventKey;
     private long nproductKey;

    public RobEventProductId() {
    }

    public RobEventProductId(long neventKey, long nproductKey) {
       this.neventKey = neventKey;
       this.nproductKey = nproductKey;
    }

    @Column(name="NEVENT_KEY", nullable=false, precision=12, scale=0)
    public long getNeventKey() {
        return this.neventKey;
    }
    
    public void setNeventKey(long neventKey) {
        this.neventKey = neventKey;
    }


    @Column(name="NPRODUCT_KEY", nullable=false, precision=12, scale=0)
    public long getNproductKey() {
        return this.nproductKey;
    }
    
    public void setNproductKey(long nproductKey) {
        this.nproductKey = nproductKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RobEventProductId) ) return false;
		 RobEventProductId castOther = ( RobEventProductId ) other; 
         
		 return (this.getNeventKey()==castOther.getNeventKey())
 && (this.getNproductKey()==castOther.getNproductKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNeventKey();
         result = 37 * result + (int) this.getNproductKey();
         return result;
   }   


}


