package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Dec 16, 2021 3:22:02 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SkyMarIlDetailId generated by hbm2java
 */
@Embeddable
public class SkyMarIlDetailId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long npackinglistIndexKey;
	private long npackinglistDetailKey;
	private String cpackinglist;

	public SkyMarIlDetailId() {
	}

	public SkyMarIlDetailId(final long npackinglistIndexKey, final long npackinglistDetailKey, final String cpackinglist) {
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.npackinglistDetailKey = npackinglistDetailKey;
		this.cpackinglist = cpackinglist;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(final long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NPACKINGLIST_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistDetailKey() {
		return this.npackinglistDetailKey;
	}

	public void setNpackinglistDetailKey(final long npackinglistDetailKey) {
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Column(name = "CPACKINGLIST", nullable = false, length = 18)
	public String getCpackinglist() {
		return this.cpackinglist;
	}

	public void setCpackinglist(final String cpackinglist) {
		this.cpackinglist = cpackinglist;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof SkyMarIlDetailId)) {
			return false;
		}
		final SkyMarIlDetailId castOther = (SkyMarIlDetailId) other;

		return (this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey())
				&& (this.getNpackinglistDetailKey() == castOther.getNpackinglistDetailKey())
				&& ((this.getCpackinglist() == castOther.getCpackinglist()) || (this.getCpackinglist() != null
						&& castOther.getCpackinglist() != null && this.getCpackinglist().equals(castOther.getCpackinglist())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNpackinglistDetailKey();
		result = 37 * result + (getCpackinglist() == null ? 0 : this.getCpackinglist().hashCode());
		return result;
	}

}
