package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated Dec 16, 2021 3:22:02 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SkyMarIlId generated by hbm2java
 */
@Embeddable
public class SkyMarIlId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long npackinglistIndexKey;
	private long npackinglistDetailKey;

	public SkyMarIlId() {
	}

	public SkyMarIlId(final long npackinglistIndexKey, final long npackinglistDetailKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(final long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NPACKINGLIST_DETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistDetailKey() {
		return this.npackinglistDetailKey;
	}

	public void setNpackinglistDetailKey(final long npackinglistDetailKey) {
		this.npackinglistDetailKey = npackinglistDetailKey;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof SkyMarIlId)) {
			return false;
		}
		final SkyMarIlId castOther = (SkyMarIlId) other;

		return (this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey())
				&& (this.getNpackinglistDetailKey() == castOther.getNpackinglistDetailKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNpackinglistDetailKey();
		return result;
	}

}
