package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 18.03.2019 12:50:53 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysAppProductGroupId generated by hbm2java
 */
@Embeddable
public class SysAppProductGroupId  implements java.io.Serializable {

     /** serialVersionUID */
     private static final long serialVersionUID = 1L;
     
     private String capp;
     private long nproctIndexKey;

    public SysAppProductGroupId() {
    }

    public SysAppProductGroupId(String capp, long nproctIndexKey) {
       this.capp = capp;
       this.nproctIndexKey = nproctIndexKey;
    }
   


    @Column(name="CAPP", nullable=false, length=40)
    public String getCapp() {
        return this.capp;
    }
    
    public void setCapp(String capp) {
        this.capp = capp;
    }


    @Column(name="NPROCT_INDEX_KEY", nullable=false, precision=12, scale=0)
    public long getNproctIndexKey() {
        return this.nproctIndexKey;
    }
    
    public void setNproctIndexKey(long nproctIndexKey) {
        this.nproctIndexKey = nproctIndexKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysAppProductGroupId) ) return false;
		 SysAppProductGroupId castOther = ( SysAppProductGroupId ) other; 
         
		 return ( (this.getCapp()==castOther.getCapp()) || ( this.getCapp()!=null && castOther.getCapp()!=null && this.getCapp().equals(castOther.getCapp()) ) )
 && (this.getNproctIndexKey()==castOther.getNproctIndexKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCapp() == null ? 0 : this.getCapp().hashCode() );
         result = 37 * result + (int) this.getNproctIndexKey();
         return result;
   }   


}


