package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysLoginRolesId generated by hbm2java
 */
@Embeddable
public class SysLoginRolesId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private int nuserId;
	private int nroleId;

	public SysLoginRolesId() {
	}

	public SysLoginRolesId(final int nuserId, final int nroleId) {
		this.nuserId = nuserId;
		this.nroleId = nroleId;
	}

	@Column(name = "NUSER_ID", nullable = false, precision = 5, scale = 0)
	public int getNuserId() {
		return this.nuserId;
	}

	public void setNuserId(final int nuserId) {
		this.nuserId = nuserId;
	}

	@Column(name = "NROLE_ID", nullable = false, precision = 5, scale = 0)
	public int getNroleId() {
		return this.nroleId;
	}

	public void setNroleId(final int nroleId) {
		this.nroleId = nroleId;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysLoginRolesId)) {
			return false;
		}
		final SysLoginRolesId castOther = (SysLoginRolesId) other;

		return this.getNuserId() == castOther.getNuserId()
				&& this.getNroleId() == castOther.getNroleId();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNuserId();
		result = 37 * result + this.getNroleId();
		return result;
	}

}
