package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:34:11 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysLoginGroupsId generated by hbm2java
 */
@Embeddable
public class SysLoginGroupsId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private int nuserId;
	private long nroleGroupkey;

	public SysLoginGroupsId() {
	}

	public SysLoginGroupsId(final int nuserId, final long nroleGroupkey) {
		this.nuserId = nuserId;
		this.nroleGroupkey = nroleGroupkey;
	}

	@Column(name = "NUSER_ID", nullable = false, precision = 5, scale = 0)
	public int getNuserId() {
		return this.nuserId;
	}

	public void setNuserId(final int nuserId) {
		this.nuserId = nuserId;
	}

	@Column(name = "NROLE_GROUPKEY", nullable = false, precision = 12, scale = 0)
	public long getNroleGroupkey() {
		return this.nroleGroupkey;
	}

	public void setNroleGroupkey(final long nroleGroupkey) {
		this.nroleGroupkey = nroleGroupkey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysLoginGroupsId)) {
			return false;
		}
		final SysLoginGroupsId castOther = (SysLoginGroupsId) other;

		return this.getNuserId() == castOther.getNuserId()
				&& this.getNroleGroupkey() == castOther.getNroleGroupkey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNuserId();
		result = 37 * result + (int) this.getNroleGroupkey();
		return result;
	}

}
