package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysLogosPicturesId generated by hbm2java
 */
@Embeddable
public class SysLogosPicturesId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nlogoKey;
	private int ncolored;

	public SysLogosPicturesId() {
	}

	public SysLogosPicturesId(final long nlogoKey, final int ncolored) {
		this.nlogoKey = nlogoKey;
		this.ncolored = ncolored;
	}

	@Column(name = "NLOGO_KEY", nullable = false, precision = 12, scale = 0)
	public long getNlogoKey() {
		return this.nlogoKey;
	}

	public void setNlogoKey(final long nlogoKey) {
		this.nlogoKey = nlogoKey;
	}

	@Column(name = "NCOLORED", nullable = false, precision = 1, scale = 0)
	public int getNcolored() {
		return this.ncolored;
	}

	public void setNcolored(final int ncolored) {
		this.ncolored = ncolored;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysLogosPicturesId)) {
			return false;
		}
		final SysLogosPicturesId castOther = (SysLogosPicturesId) other;

		return this.getNlogoKey() == castOther.getNlogoKey()
				&& this.getNcolored() == castOther.getNcolored();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNlogoKey();
		result = 37 * result + this.getNcolored();
		return result;
	}

}
