/*
 * SysMsgSubscriberId.java
 *
 * Copyright (c) 2015-2015 Lufthansa Industry Solutions AS GmbH. All Rights Reserved.
 *
 */
package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 29.01.2016 12:07:25 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysMsgSubscriberId generated by hbm2java
 */
@Embeddable
public class SysMsgSubscriberId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String cqueue;

	private String ctopic;

	public SysMsgSubscriberId() {
	}

	public SysMsgSubscriberId(final String cqueue, final String ctopic) {
		this.cqueue = cqueue;
		this.ctopic = ctopic;
	}

	@Column(name = "CQUEUE", nullable = false, length = 256)
	public String getCqueue() {
		return this.cqueue;
	}

	public void setCqueue(final String cqueue) {
		this.cqueue = cqueue;
	}

	@Column(name = "CTOPIC", nullable = false, length = 256)
	public String getCtopic() {
		return this.ctopic;
	}

	public void setCtopic(final String ctopic) {
		this.ctopic = ctopic;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysMsgSubscriberId)) {
			return false;
		}
		final SysMsgSubscriberId castOther = (SysMsgSubscriberId) other;

		return (this.getCqueue() == castOther.getCqueue()
				|| this.getCqueue() != null && castOther.getCqueue() != null && this.getCqueue().equals(castOther.getCqueue()))
				&& (this.getCtopic() == castOther.getCtopic()
						|| this.getCtopic() != null && castOther.getCtopic() != null && this.getCtopic().equals(castOther.getCtopic()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCqueue() == null ? 0 : this.getCqueue().hashCode());
		result = 37 * result + (getCtopic() == null ? 0 : this.getCtopic().hashCode());
		return result;
	}

}
