package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 29.01.2016 12:07:25 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysMsgDeliveryId generated by hbm2java
 */
@Embeddable
public class SysMsgDeliveryId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private String cqueue;
	private long nmessageKey;

	public SysMsgDeliveryId() {
	}

	public SysMsgDeliveryId(final String cqueue, final long nmessageKey) {
		this.cqueue = cqueue;
		this.nmessageKey = nmessageKey;
	}

	@Column(name = "CQUEUE", nullable = false, length = 256)
	public String getCqueue() {
		return this.cqueue;
	}

	public void setCqueue(final String cqueue) {
		this.cqueue = cqueue;
	}

	@Column(name = "NMESSAGE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNmessageKey() {
		return this.nmessageKey;
	}

	public void setNmessageKey(final long nmessageKey) {
		this.nmessageKey = nmessageKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysMsgDeliveryId)) {
			return false;
		}
		final SysMsgDeliveryId castOther = (SysMsgDeliveryId) other;

		return (this.getCqueue() == castOther.getCqueue()
				|| this.getCqueue() != null && castOther.getCqueue() != null && this.getCqueue().equals(castOther.getCqueue()))
				&& this.getNmessageKey() == castOther.getNmessageKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCqueue() == null ? 0 : this.getCqueue().hashCode());
		result = 37 * result + (int) this.getNmessageKey();
		return result;
	}

}
