package com.lsgskychefs.cbase.middleware.persistence.domain;

// Generated 22.09.2014 12:31:47 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SysPpmRules generated by hbm2java
 */
@Entity
@NamedEntityGraph(name = "SysPpmRules.sysPpmGroups", attributeNodes = @NamedAttributeNode("sysPpmGroups"))
@Table(name = "SYS_PPM_RULES")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class SysPpmRules implements DomainObject, java.io.Serializable {

	// Reference to sysPpmActions (per nalert_level) is deprecated! releation through ppmGroups! May Column/FK should be deleted!
	// private SysPpmActions sysPpmActions;

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nruleKey;

	private String ctype;

	private int nless;

	private int ngreater;

	private int nequal;

	private BigDecimal nvalue;

	private long ncolor;

	private String ctopic;

	private Set<SysPpmGroup> sysPpmGroups = new HashSet<>(0);

	@Id
	@Column(name = "NRULE_KEY", unique = true, nullable = false, precision = 12, scale = 0)
	public long getNruleKey() {
		return this.nruleKey;
	}

	public void setNruleKey(final long nruleKey) {
		this.nruleKey = nruleKey;
	}

	@Column(name = "CTYPE", nullable = false, length = 4)
	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(final String ctype) {
		this.ctype = ctype;
	}

	@Column(name = "NLESS", nullable = false, precision = 1, scale = 0)
	public int getNless() {
		return this.nless;
	}

	public void setNless(final int nless) {
		this.nless = nless;
	}

	@Column(name = "NGREATER", nullable = false, precision = 1, scale = 0)
	public int getNgreater() {
		return this.ngreater;
	}

	public void setNgreater(final int ngreater) {
		this.ngreater = ngreater;
	}

	@Column(name = "NEQUAL", nullable = false, precision = 1, scale = 0)
	public int getNequal() {
		return this.nequal;
	}

	public void setNequal(final int nequal) {
		this.nequal = nequal;
	}

	@Column(name = "NVALUE", nullable = false, precision = 12, scale = 2)
	public BigDecimal getNvalue() {
		return this.nvalue;
	}

	public void setNvalue(final BigDecimal nvalue) {
		this.nvalue = nvalue;
	}

	@Column(name = "NCOLOR", nullable = false, precision = 12, scale = 0)
	public long getNcolor() {
		return this.ncolor;
	}

	public void setNcolor(final long ncolor) {
		this.ncolor = ncolor;
	}

	@Column(name = "CTOPIC", length = 25)
	public String getCtopic() {
		return this.ctopic;
	}

	public void setCtopic(final String ctopic) {
		this.ctopic = ctopic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysPpmRules")
	@JsonBackReference
	public Set<SysPpmGroup> getSysPpmGroups() {
		return this.sysPpmGroups;
	}

	public void setSysPpmGroups(final Set<SysPpmGroup> sysPpmGroups) {
		this.sysPpmGroups = sysPpmGroups;
	}

}
