package com.lsgskychefs.cbase.middleware.persistence.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysPpmGroupId generated by hbm2java
 */
@Embeddable
public class SysPpmGroupId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int ngroupKey;

	private int nruleKey;

	@Column(name = "NGROUP_KEY", nullable = false, precision = 6, scale = 0)
	public int getNgroupKey() {
		return this.ngroupKey;
	}

	public void setNgroupKey(final int ngroupKey) {
		this.ngroupKey = ngroupKey;
	}

	@Column(name = "NRULE_KEY", nullable = false, precision = 6, scale = 0)
	public int getNruleKey() {
		return this.nruleKey;
	}

	public void setNruleKey(final int nruleKey) {
		this.nruleKey = nruleKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysPpmGroupId)) {
			return false;
		}
		final SysPpmGroupId castOther = (SysPpmGroupId) other;

		return this.getNgroupKey() == castOther.getNgroupKey()
				&& this.getNruleKey() == castOther.getNruleKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNgroupKey();
		result = 37 * result + this.getNruleKey();
		return result;
	}

}
