package com.lsgskychefs.cbase.middleware.persistence.domain;

// Generated 22.09.2014 12:31:47 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedEntityGraphs;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * SysPpmGroup generated by hbm2java
 */
@Entity
@NamedEntityGraphs({
		@NamedEntityGraph(name = "SysPpmGroup.sysPpmRules", attributeNodes = @NamedAttributeNode("sysPpmRules")),
		@NamedEntityGraph(name = "SysPpmGroup.sysPpmActions", attributeNodes = @NamedAttributeNode("sysPpmActions"))
})
@Table(name = "SYS_PPM_GROUP")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class SysPpmGroup implements DomainObject, java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private SysPpmGroupId id;
	private SysPpmRules sysPpmRules;
	private SysPpmActions sysPpmActions;
	private int nautoStop;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ngroupKey", column = @Column(name = "NGROUP_KEY", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "nruleKey", column = @Column(name = "NRULE_KEY", nullable = false, precision = 6, scale = 0)) })
	public SysPpmGroupId getId() {
		return this.id;
	}

	public void setId(final SysPpmGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NRULE_KEY", nullable = false, insertable = false, updatable = false)
	@JsonManagedReference
	public SysPpmRules getSysPpmRules() {
		return this.sysPpmRules;
	}

	public void setSysPpmRules(final SysPpmRules sysPpmRules) {
		this.sysPpmRules = sysPpmRules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NALERT_LEVEL")
	@JsonBackReference
	public SysPpmActions getSysPpmActions() {
		return this.sysPpmActions;
	}

	public void setSysPpmActions(final SysPpmActions sysPpmActions) {
		this.sysPpmActions = sysPpmActions;
	}

	@Column(name = "NAUTO_STOP", nullable = false, precision = 1, scale = 0)
	public int getNautoStop() {
		return this.nautoStop;
	}

	public void setNautoStop(final int nautoStop) {
		this.nautoStop = nautoStop;
	}

}
