package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysPackinglistTypeId generated by hbm2java
 */
@Embeddable
public class SysPackinglistTypeId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private String cclient;
	private String cpackinglistMatch;
	private int npackinglist1stGroup;
	private int npackinglist2ndGroup;

	public SysPackinglistTypeId() {
	}

	public SysPackinglistTypeId(final String cclient, final String cpackinglistMatch, final int npackinglist1stGroup,
			final int npackinglist2ndGroup) {
		this.cclient = cclient;
		this.cpackinglistMatch = cpackinglistMatch;
		this.npackinglist1stGroup = npackinglist1stGroup;
		this.npackinglist2ndGroup = npackinglist2ndGroup;
	}

	@Column(name = "CCLIENT", nullable = false, length = 3)
	public String getCclient() {
		return this.cclient;
	}

	public void setCclient(final String cclient) {
		this.cclient = cclient;
	}

	@Column(name = "CPACKINGLIST_MATCH", nullable = false, length = 18)
	public String getCpackinglistMatch() {
		return this.cpackinglistMatch;
	}

	public void setCpackinglistMatch(final String cpackinglistMatch) {
		this.cpackinglistMatch = cpackinglistMatch;
	}

	@Column(name = "NPACKINGLIST_1ST_GROUP", nullable = false, precision = 6, scale = 0)
	public int getNpackinglist1stGroup() {
		return this.npackinglist1stGroup;
	}

	public void setNpackinglist1stGroup(final int npackinglist1stGroup) {
		this.npackinglist1stGroup = npackinglist1stGroup;
	}

	@Column(name = "NPACKINGLIST_2ND_GROUP", nullable = false, precision = 6, scale = 0)
	public int getNpackinglist2ndGroup() {
		return this.npackinglist2ndGroup;
	}

	public void setNpackinglist2ndGroup(final int npackinglist2ndGroup) {
		this.npackinglist2ndGroup = npackinglist2ndGroup;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysPackinglistTypeId)) {
			return false;
		}
		final SysPackinglistTypeId castOther = (SysPackinglistTypeId) other;

		return (this.getCclient() == castOther.getCclient()
				|| this.getCclient() != null && castOther.getCclient() != null && this.getCclient().equals(castOther.getCclient()))
				&& (this.getCpackinglistMatch() == castOther.getCpackinglistMatch()
						|| this.getCpackinglistMatch() != null && castOther.getCpackinglistMatch() != null
								&& this.getCpackinglistMatch().equals(castOther.getCpackinglistMatch()))
				&& this.getNpackinglist1stGroup() == castOther.getNpackinglist1stGroup()
				&& this.getNpackinglist2ndGroup() == castOther.getNpackinglist2ndGroup();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCclient() == null ? 0 : this.getCclient().hashCode());
		result = 37 * result + (getCpackinglistMatch() == null ? 0 : this.getCpackinglistMatch().hashCode());
		result = 37 * result + this.getNpackinglist1stGroup();
		result = 37 * result + this.getNpackinglist2ndGroup();
		return result;
	}

}
