package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 04.02.2016 14:09:57 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * SysQueueFlightMealsId generated by hbm2java
 */
@Embeddable
public class SysQueueFlightMealsId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long njobNr;
	private long ndetailKey;

	public SysQueueFlightMealsId() {
	}

	public SysQueueFlightMealsId(final long njobNr, final long ndetailKey) {
		this.njobNr = njobNr;
		this.ndetailKey = ndetailKey;
	}

	@Column(name = "NJOB_NR", nullable = false, precision = 12, scale = 0)
	public long getNjobNr() {
		return this.njobNr;
	}

	public void setNjobNr(final long njobNr) {
		this.njobNr = njobNr;
	}

	@Column(name = "NDETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNdetailKey() {
		return this.ndetailKey;
	}

	public void setNdetailKey(final long ndetailKey) {
		this.ndetailKey = ndetailKey;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysQueueFlightMealsId)) {
			return false;
		}
		final SysQueueFlightMealsId castOther = (SysQueueFlightMealsId) other;

		return this.getNjobNr() == castOther.getNjobNr()
				&& this.getNdetailKey() == castOther.getNdetailKey();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNjobNr();
		result = 37 * result + (int) this.getNdetailKey();
		return result;
	}

	/** {@inheritDoc} */
	@Override
	public String asString() {
		return ToStringBuilder.reflectionToString(this);
	}

}
