package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysQueueBatchSubdetailId generated by hbm2java
 */
@Embeddable
public class SysQueueBatchSubdetailId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long ndetailKey;
	private long nlfdNr;

	public SysQueueBatchSubdetailId() {
	}

	public SysQueueBatchSubdetailId(final long ndetailKey, final long nlfdNr) {
		this.ndetailKey = ndetailKey;
		this.nlfdNr = nlfdNr;
	}

	@Column(name = "NDETAIL_KEY", nullable = false, precision = 12, scale = 0)
	public long getNdetailKey() {
		return this.ndetailKey;
	}

	public void setNdetailKey(final long ndetailKey) {
		this.ndetailKey = ndetailKey;
	}

	@Column(name = "NLFD_NR", nullable = false, precision = 12, scale = 0)
	public long getNlfdNr() {
		return this.nlfdNr;
	}

	public void setNlfdNr(final long nlfdNr) {
		this.nlfdNr = nlfdNr;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysQueueBatchSubdetailId)) {
			return false;
		}
		final SysQueueBatchSubdetailId castOther = (SysQueueBatchSubdetailId) other;

		return this.getNdetailKey() == castOther.getNdetailKey()
				&& this.getNlfdNr() == castOther.getNlfdNr();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNdetailKey();
		result = 37 * result + (int) this.getNlfdNr();
		return result;
	}

}
