package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 09.06.2016 16:01:51 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysQueueFlightSpmlId generated by hbm2java
 */
@Embeddable
public class SysQueueFlightSpmlId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long njobNr;
	private String cclass;
	private int nprio;

	public SysQueueFlightSpmlId() {
	}

	public SysQueueFlightSpmlId(final long njobNr, final String cclass, final int nprio) {
		this.njobNr = njobNr;
		this.cclass = cclass;
		this.nprio = nprio;
	}

	@Column(name = "NJOB_NR", nullable = false, precision = 12, scale = 0)
	public long getNjobNr() {
		return this.njobNr;
	}

	public void setNjobNr(final long njobNr) {
		this.njobNr = njobNr;
	}

	@Column(name = "CCLASS", nullable = false, length = 10)
	public String getCclass() {
		return this.cclass;
	}

	public void setCclass(final String cclass) {
		this.cclass = cclass;
	}

	@Column(name = "NPRIO", nullable = false, precision = 6, scale = 0)
	public int getNprio() {
		return this.nprio;
	}

	public void setNprio(final int nprio) {
		this.nprio = nprio;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysQueueFlightSpmlId)) {
			return false;
		}
		final SysQueueFlightSpmlId castOther = (SysQueueFlightSpmlId) other;

		return this.getNjobNr() == castOther.getNjobNr()
				&& (this.getCclass() == castOther.getCclass()
						|| this.getCclass() != null && castOther.getCclass() != null && this.getCclass().equals(castOther.getCclass()))
				&& this.getNprio() == castOther.getNprio();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNjobNr();
		result = 37 * result + (getCclass() == null ? 0 : this.getCclass().hashCode());
		result = 37 * result + this.getNprio();
		return result;
	}

}
