package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 19.05.2016 11:54:46 by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysQueueFlightPaxId generated by hbm2java
 */
@Embeddable
public class SysQueueFlightPaxId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long njobNr;
	private String cclass;

	public SysQueueFlightPaxId() {
	}

	public SysQueueFlightPaxId(final long njobNr, final String cclass) {
		this.njobNr = njobNr;
		this.cclass = cclass;
	}

	@Column(name = "NJOB_NR", nullable = false, precision = 12, scale = 0)
	public long getNjobNr() {
		return this.njobNr;
	}

	public void setNjobNr(final long njobNr) {
		this.njobNr = njobNr;
	}

	@Column(name = "CCLASS", nullable = false, length = 10)
	public String getCclass() {
		return this.cclass;
	}

	public void setCclass(final String cclass) {
		this.cclass = cclass;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysQueueFlightPaxId)) {
			return false;
		}
		final SysQueueFlightPaxId castOther = (SysQueueFlightPaxId) other;

		return this.getNjobNr() == castOther.getNjobNr()
				&& (this.getCclass() == castOther.getCclass()
						|| this.getCclass() != null && castOther.getCclass() != null && this.getCclass().equals(castOther.getCclass()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNjobNr();
		result = 37 * result + (getCclass() == null ? 0 : this.getCclass().hashCode());
		return result;
	}

}
