package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysQueueBatchSpcId generated by hbm2java
 */
@Embeddable
public class SysQueueBatchSpcId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long njobNr;
	private long npackinglistIndexKey;
	private long nairlineKey;
	private String cunit;
	private Date dvalidFrom;

	public SysQueueBatchSpcId() {
	}

	public SysQueueBatchSpcId(final long njobNr, final long npackinglistIndexKey, final long nairlineKey, final String cunit,
			final Date dvalidFrom) {
		this.njobNr = njobNr;
		this.npackinglistIndexKey = npackinglistIndexKey;
		this.nairlineKey = nairlineKey;
		this.cunit = cunit;
		this.dvalidFrom = dvalidFrom;
	}

	@Column(name = "NJOB_NR", nullable = false, precision = 12, scale = 0)
	public long getNjobNr() {
		return this.njobNr;
	}

	public void setNjobNr(final long njobNr) {
		this.njobNr = njobNr;
	}

	@Column(name = "NPACKINGLIST_INDEX_KEY", nullable = false, precision = 12, scale = 0)
	public long getNpackinglistIndexKey() {
		return this.npackinglistIndexKey;
	}

	public void setNpackinglistIndexKey(final long npackinglistIndexKey) {
		this.npackinglistIndexKey = npackinglistIndexKey;
	}

	@Column(name = "NAIRLINE_KEY", nullable = false, precision = 12, scale = 0)
	public long getNairlineKey() {
		return this.nairlineKey;
	}

	public void setNairlineKey(final long nairlineKey) {
		this.nairlineKey = nairlineKey;
	}

	@Column(name = "CUNIT", nullable = false, length = 4)
	public String getCunit() {
		return this.cunit;
	}

	public void setCunit(final String cunit) {
		this.cunit = cunit;
	}

	@Column(name = "DVALID_FROM", nullable = false, length = 7)
	public Date getDvalidFrom() {
		return this.dvalidFrom;
	}

	public void setDvalidFrom(final Date dvalidFrom) {
		this.dvalidFrom = dvalidFrom;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysQueueBatchSpcId)) {
			return false;
		}
		final SysQueueBatchSpcId castOther = (SysQueueBatchSpcId) other;

		return this.getNjobNr() == castOther.getNjobNr()
				&& this.getNpackinglistIndexKey() == castOther.getNpackinglistIndexKey()
				&& this.getNairlineKey() == castOther.getNairlineKey()
				&& (this.getCunit() == castOther.getCunit()
						|| this.getCunit() != null && castOther.getCunit() != null && this.getCunit().equals(castOther.getCunit()))
				&& (this.getDvalidFrom() == castOther.getDvalidFrom() || this.getDvalidFrom() != null
						&& castOther.getDvalidFrom() != null && this.getDvalidFrom().equals(castOther.getDvalidFrom()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNjobNr();
		result = 37 * result + (int) this.getNpackinglistIndexKey();
		result = 37 * result + (int) this.getNairlineKey();
		result = 37 * result + (getCunit() == null ? 0 : this.getCunit().hashCode());
		result = 37 * result + (getDvalidFrom() == null ? 0 : this.getDvalidFrom().hashCode());
		return result;
	}

}
