package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 01.12.2015 16:57:35 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRoleGroupsDetailId generated by hbm2java
 */
@Embeddable
public class SysRoleGroupsDetailId extends AbstractDomainObjectPK implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	private long nroleGroupkey;
	private int nroleId;

	public SysRoleGroupsDetailId() {
	}

	public SysRoleGroupsDetailId(final long nroleGroupkey, final int nroleId) {
		this.nroleGroupkey = nroleGroupkey;
		this.nroleId = nroleId;
	}

	@Column(name = "NROLE_GROUPKEY", nullable = false, precision = 12, scale = 0)
	public long getNroleGroupkey() {
		return this.nroleGroupkey;
	}

	public void setNroleGroupkey(final long nroleGroupkey) {
		this.nroleGroupkey = nroleGroupkey;
	}

	@Column(name = "NROLE_ID", nullable = false, precision = 5, scale = 0)
	public int getNroleId() {
		return this.nroleId;
	}

	public void setNroleId(final int nroleId) {
		this.nroleId = nroleId;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof SysRoleGroupsDetailId)) {
			return false;
		}
		final SysRoleGroupsDetailId castOther = (SysRoleGroupsDetailId) other;

		return this.getNroleGroupkey() == castOther.getNroleGroupkey()
				&& this.getNroleId() == castOther.getNroleId();
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNroleGroupkey();
		result = 37 * result + this.getNroleId();
		return result;
	}

}
