package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 10.01.2017 13:42:37 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRemotePrinterSetupId generated by hbm2java
 */
@Embeddable
public class SysRemotePrinterSetupId implements java.io.Serializable {
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long nprinterKey;
	private long njobType;

	public SysRemotePrinterSetupId() {
	}

	public SysRemotePrinterSetupId(final long nprinterKey, final long njobType) {
		this.nprinterKey = nprinterKey;
		this.njobType = njobType;
	}

	@Column(name = "NPRINTER_KEY", nullable = false, precision = 12, scale = 0)
	public long getNprinterKey() {
		return this.nprinterKey;
	}

	public void setNprinterKey(final long nprinterKey) {
		this.nprinterKey = nprinterKey;
	}

	@Column(name = "NJOB_TYPE", nullable = false, precision = 12, scale = 0)
	public long getNjobType() {
		return this.njobType;
	}

	public void setNjobType(final long njobType) {
		this.njobType = njobType;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof SysRemotePrinterSetupId)) {
			return false;
		}
		final SysRemotePrinterSetupId castOther = (SysRemotePrinterSetupId) other;

		return (this.getNprinterKey() == castOther.getNprinterKey())
				&& (this.getNjobType() == castOther.getNjobType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNprinterKey();
		result = 37 * result + (int) this.getNjobType();
		return result;
	}

}
