package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 31.05.2021 11:06:51 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRemotePrinterFuncId generated by hbm2java
 */
@Embeddable
public class SysRemotePrinterFuncId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private long njobType;
	private int njobSubtype;

	public SysRemotePrinterFuncId() {
	}

	public SysRemotePrinterFuncId(long njobType, int njobSubtype) {
		this.njobType = njobType;
		this.njobSubtype = njobSubtype;
	}

	@Column(name = "NJOB_TYPE", nullable = false, precision = 12, scale = 0)
	public long getNjobType() {
		return this.njobType;
	}

	public void setNjobType(long njobType) {
		this.njobType = njobType;
	}

	@Column(name = "NJOB_SUBTYPE", nullable = false, precision = 2, scale = 0)
	public int getNjobSubtype() {
		return this.njobSubtype;
	}

	public void setNjobSubtype(int njobSubtype) {
		this.njobSubtype = njobSubtype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysRemotePrinterFuncId))
			return false;
		SysRemotePrinterFuncId castOther = (SysRemotePrinterFuncId) other;

		return (this.getNjobType() == castOther.getNjobType())
				&& (this.getNjobSubtype() == castOther.getNjobSubtype());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNjobType();
		result = 37 * result + this.getNjobSubtype();
		return result;
	}
}


