package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 05.05.2020 10:58:44 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysServicesAliveId generated by hbm2java
 */
@Embeddable
public class SysServicesAliveId implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String cservice;

	private String cinstance;

	public SysServicesAliveId() {
	}

	public SysServicesAliveId(final String cservice, final String cinstance) {
		this.cservice = cservice;
		this.cinstance = cinstance;
	}

	@Column(name = "CSERVICE", nullable = false, length = 100)
	public String getCservice() {
		return this.cservice;
	}

	public void setCservice(final String cservice) {
		this.cservice = cservice;
	}

	@Column(name = "CINSTANCE", nullable = false, length = 50)
	public String getCinstance() {
		return this.cinstance;
	}

	public void setCinstance(final String cinstance) {
		this.cinstance = cinstance;
	}

	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof SysServicesAliveId)) {
			return false;
		}
		final SysServicesAliveId castOther = (SysServicesAliveId) other;

		return ((this.getCservice() == castOther.getCservice())
				|| (this.getCservice() != null && castOther.getCservice() != null && this.getCservice().equals(castOther.getCservice())))
				&& ((this.getCinstance() == castOther.getCinstance()) || (this.getCinstance() != null && castOther.getCinstance() != null
						&& this.getCinstance().equals(castOther.getCinstance())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCservice() == null ? 0 : this.getCservice().hashCode());
		result = 37 * result + (getCinstance() == null ? 0 : this.getCinstance().hashCode());
		return result;
	}

}
