package com.lsgskychefs.cbase.middleware.persistence.domain;
// Generated 25.08.2022 13:45:52 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysServiceCompresDetId generated by hbm2java
 */
@Embeddable
public class SysServiceCompresDetId  implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

     private long nserviceCompres;
     private long ndetailKey;

    public SysServiceCompresDetId() {
    }

    public SysServiceCompresDetId(long nserviceCompres, long ndetailKey) {
       this.nserviceCompres = nserviceCompres;
       this.ndetailKey = ndetailKey;
    }

    @Column(name="NSERVICE_COMPRES", nullable=false, precision=12, scale=0)
    public long getNserviceCompres() {
        return this.nserviceCompres;
    }
    
    public void setNserviceCompres(long nserviceCompres) {
        this.nserviceCompres = nserviceCompres;
    }


    @Column(name="NDETAIL_KEY", nullable=false, precision=12, scale=0)
    public long getNdetailKey() {
        return this.ndetailKey;
    }
    
    public void setNdetailKey(long ndetailKey) {
        this.ndetailKey = ndetailKey;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysServiceCompresDetId) ) return false;
		 SysServiceCompresDetId castOther = ( SysServiceCompresDetId ) other; 
         
		 return (this.getNserviceCompres()==castOther.getNserviceCompres())
 && (this.getNdetailKey()==castOther.getNdetailKey());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNserviceCompres();
         result = 37 * result + (int) this.getNdetailKey();
         return result;
   }   


}


